"""Terminology: directed acyclic graph (DAG); identifier (ID); JavaScript Object Notation (JSON); Secure Hash Algorithm 256-bit (SHA-256); benchmark specification graph (BENCH); verifiable execution environment (ENV); model reproducibility specification (MODEL); generative simulation specification (SIM); software self-assembly (verifier-ssa); software self-improvement (verifier-ssi); candidate self-replication (verifier-ssr); Verifier Standard (VSTD).

verifier-2.0.0: Incorrigible Tesla caged sandboxing, GRAPH, ENV, BENCH, DATA, HYPER, MODEL, and SIM risk profile and simulation representation.

Experimental, non-normative declarations and local consistency checks. These
draft identifiers do not establish the existing numbered profiles. No physical
sandbox, authenticated hardware attestation, inductive proof, or distributed
consensus is implemented. See docs/V2_CANDIDATE.md for executable boundaries.
"""

from __future__ import annotations

from .benchmark import (
    BenchmarkGamingError,
    BenchmarkProblem,
    BenchmarkSuite,
    CapabilityDimension,
    ComplexityClass,
    EpistemicStratum,
    FormalLanguage,
    OracleMechanism,
    ProblemBasis,
    ProblemEvaluationOutcome,
    ProblemReceipt,
)
from .data import (
    ContaminationError,
    ContaminationReport,
    ContaminationVerdict,
    DataShard,
    DatasetError,
    DatasetManifest,
    DatasetSplit,
    compute_merkle_root,
    detect_benchmark_contamination,
)
from .environment import (
    EnvironmentDriftError,
    EnvironmentError,
    EnvironmentIsolationTier,
    EnvironmentProfile,
    ExecutionBounds,
    HardwareSubstrate,
    NetworkIsolationMode,
    SoftwareSubstrate,
    ZeroFalseConfidenceError,
)
from .graph import (
    AcyclicityViolationError,
    CausalDirection,
    EpistemicStatus,
    GraphEdge,
    GraphNode,
    GraphNodeKind,
    GraphProvenanceError,
    LineageBrokenError,
    ProvenanceDAG,
)
from .hyperparameters import (
    CheckpointLineageBrokenError,
    CheckpointLineageDAG,
    CheckpointNode,
    HyperparameterError,
    HyperparameterManifest,
    PrecisionType,
    TrainingStepReceipt,
)
from .model import (
    CorrigibilityDefectError,
    CurriculumPillarStatus,
    DeceptiveAlignmentDetectedError,
    ModelReproducibilityError,
    ModelReproducibilityProfile,
    RefutationChallenge,
    SuperintelligenceRiskFacets,
    verify_refutation_challenges,
)
from .risk_profile import (
    OverallContainmentVerdict,
    Vstd160RiskProfileReceipt,
    Vstd200RiskProfileReceipt,
    evaluate_vstd160_risk_profile,
    evaluate_vstd200_risk_profile,
)
from .simulation import (
    AbstractSimulationManifest,
    AgentParityContainmentError,
    BisimulationAbstractionError,
    CausalOrderingKind,
    DeterminismViolationError,
    DistributedShardingError,
    InvariantSafetyViolationError,
    SecondOrderHyperOntology,
    SimulationError,
    SimulationTier,
    SimulationVerdict,
    StateSnapshot,
    StateTopologyType,
    VstdSimReceipt,
    compute_state_digest,
    compute_trajectory_root_digest,
    evaluate_vstd_sim_receipt,
    verify_sim1_trace_replay,
    verify_sim2_invariant_safety,
    verify_sim3_bisimulation_abstraction,
    verify_sim4_agent_parity_contained,
    verify_sim5_distributed_sharded,
)
from .tesla_cage import (
    AnalogPowerRelayAttestation,
    ContainmentBreachType,
    ContainmentTier,
    ContainmentViolationError,
    HardwareAttestationPrimitive,
    HardwareDiodeAttestation,
    OperatorTerminationReceipt,
    ShutdownResistanceError,
    SubstrateImmunityViolationError,
    TeslaCageSandbox,
)

__all__ = [
    # Graph
    "AcyclicityViolationError",
    "CausalDirection",
    "EpistemicStatus",
    "GraphEdge",
    "GraphNode",
    "GraphNodeKind",
    "GraphProvenanceError",
    "LineageBrokenError",
    "ProvenanceDAG",
    # Environment
    "EnvironmentDriftError",
    "EnvironmentError",
    "EnvironmentIsolationTier",
    "EnvironmentProfile",
    "ExecutionBounds",
    "HardwareSubstrate",
    "NetworkIsolationMode",
    "SoftwareSubstrate",
    "ZeroFalseConfidenceError",
    # Benchmark
    "BenchmarkGamingError",
    "BenchmarkProblem",
    "BenchmarkSuite",
    "CapabilityDimension",
    "ComplexityClass",
    "EpistemicStratum",
    "FormalLanguage",
    "OracleMechanism",
    "ProblemBasis",
    "ProblemEvaluationOutcome",
    "ProblemReceipt",
    # Data
    "ContaminationError",
    "ContaminationReport",
    "ContaminationVerdict",
    "DataShard",
    "DatasetError",
    "DatasetManifest",
    "DatasetSplit",
    "compute_merkle_root",
    "detect_benchmark_contamination",
    # Hyperparameters
    "CheckpointLineageBrokenError",
    "CheckpointLineageDAG",
    "CheckpointNode",
    "HyperparameterError",
    "HyperparameterManifest",
    "PrecisionType",
    "TrainingStepReceipt",
    # Model
    "CorrigibilityDefectError",
    "CurriculumPillarStatus",
    "DeceptiveAlignmentDetectedError",
    "ModelReproducibilityError",
    "ModelReproducibilityProfile",
    "RefutationChallenge",
    "SuperintelligenceRiskFacets",
    "verify_refutation_challenges",
    # Tesla Cage
    "AnalogPowerRelayAttestation",
    "ContainmentBreachType",
    "ContainmentTier",
    "ContainmentViolationError",
    "HardwareAttestationPrimitive",
    "HardwareDiodeAttestation",
    "OperatorTerminationReceipt",
    "ShutdownResistanceError",
    "SubstrateImmunityViolationError",
    "TeslaCageSandbox",
    # Risk Profile
    "OverallContainmentVerdict",
    "Vstd160RiskProfileReceipt",
    "Vstd200RiskProfileReceipt",
    "evaluate_vstd160_risk_profile",
    "evaluate_vstd200_risk_profile",
    # Simulation (SIM-1..5)
    "AbstractSimulationManifest",
    "AgentParityContainmentError",
    "BisimulationAbstractionError",
    "CausalOrderingKind",
    "DeterminismViolationError",
    "DistributedShardingError",
    "InvariantSafetyViolationError",
    "SecondOrderHyperOntology",
    "SimulationError",
    "SimulationTier",
    "SimulationVerdict",
    "StateSnapshot",
    "StateTopologyType",
    "VstdSimReceipt",
    "compute_state_digest",
    "compute_trajectory_root_digest",
    "evaluate_vstd_sim_receipt",
    "verify_sim1_trace_replay",
    "verify_sim2_invariant_safety",
    "verify_sim3_bisimulation_abstraction",
    "verify_sim4_agent_parity_contained",
    "verify_sim5_distributed_sharded",
]
