"""Terminology: Davis-Putnam-Logemann-Loveland (DPLL); grounded decision certificate (GDC);
JavaScript Object Notation (JSON); reverse unit propagation (RUP);
Boolean satisfiability problem (SAT); Supply Chain Integrity, Transparency, and Trust (SCITT);
unsatisfiable (UNSAT); Verifier Standard (VSTD).

First-party component inventory for exact, nonexecuting VSTD-2 planning.

``planning_surface_schema_ids`` names the modeled surface schema from which a
component may be considered. ``accepted_schema_ids`` names only explicit native
serialized input schemas; it remains empty for typed or unversioned callables.
Registry construction never imports or executes an implementation entry point.
"""

from __future__ import annotations

from verifier.interoperability.catalog import (
    ComponentAvailability,
    ComponentKind,
    ComponentLifecycle,
    InteractionMode,
    InteroperabilityComponentDescriptor,
    InteroperabilityComponentRegistry,
)


REFERENCE_CATALOG_VERSION = "VSTD-REFERENCE-COMPONENTS-1.3"
REFERENCE_CATALOG_CLAIM_BOUNDARY = (
    "Catalog membership records first-party implementation entry points for exact "
    "planning matches. It does not execute a component, prove runtime availability, "
    "establish native input validity, or grant a VSTD result."
)
_TRANSFER_PROFILE_DIGEST = "sha256:0d26f06addc32e61e0ba68a466b4721db6a8ad2a46021c96f226da7d91b410bd"
_TRANSFER_PROFILE_PATH = "src/verifier/profiles/proposition-transfer-rule-0.1.json"
_FORMATION_PROFILE_DIGEST = "sha256:271760d604e1ade55cba4974c658b92263bd3ee8ae343677dd91d0e713fb677f"
_FORMATION_PROFILE_PATH = "src/verifier/profiles/typed-formation-0.1.json"
_AUTHORITY_COMPOSITION_PROFILE_DIGEST = "sha256:61e3cb39f80878dfb57f54a34b3e7bddc0fcc71149a2c97eab162afaa754ba6c"
_FORMATION_BOUNDARY = (
    "A planned mechanism match does not establish rule-profile compatibility or execution. "
    "Finite formation does not establish source self-derivation, grounding, completeness, "
    "authority axiom agency, historical execution, implementation independence, or a silo-status upgrade."
)


def _component(
    component_id: str,
    label: str,
    kind: ComponentKind,
    implementation_ref: str,
    family_id: str,
    native_system: str,
    native_objects: tuple[str, ...],
    native_versions: tuple[str, ...],
    native_inputs: tuple[str, ...],
    native_outputs: tuple[str, ...],
    native_result_vocabulary: tuple[str, ...],
    mechanism_ids: tuple[str, ...],
    interaction_modes: tuple[InteractionMode, ...],
    *,
    lifecycle: ComponentLifecycle = ComponentLifecycle.IMPLEMENTED,
    accepted_schema_ids: tuple[str, ...] = (),
    emitted_schema_ids: tuple[str, ...] = (),
    supported_relations: tuple[str, ...] = (),
    optional_dependencies: tuple[str, ...] = (),
    trust_roots: tuple[str, ...] = (),
    domain_tags: tuple[str, ...] = (),
    additional_prerequisites: tuple[str, ...] = (),
    freshness_behavior: str,
    transformation_loss: str,
    failure_behavior: str,
    claim_boundary: str,
) -> InteroperabilityComponentDescriptor:
    return InteroperabilityComponentDescriptor(
        component_id=component_id,
        label=label,
        kind=kind,
        lifecycle=lifecycle,
        implementation_ref=implementation_ref,
        accepted_schema_ids=accepted_schema_ids,
        planning_surface_schema_ids=("VSTD-2",),
        verifier_family_ids=(family_id,),
        native_system=native_system,
        native_objects=native_objects,
        native_versions=native_versions,
        native_inputs=native_inputs,
        native_outputs=native_outputs,
        native_result_vocabulary=native_result_vocabulary,
        emitted_schema_ids=emitted_schema_ids,
        supported_relations=supported_relations,
        mechanism_ids=mechanism_ids,
        interaction_modes=interaction_modes,
        domain_tags=domain_tags,
        optional_dependencies=optional_dependencies,
        execution_prerequisites=(
            "EXACT_NATIVE_INPUT",
            "EXACT_IMPLEMENTATION_COORDINATE",
            "RESOURCE_BOUNDS",
            *additional_prerequisites,
        ),
        trust_roots=trust_roots,
        freshness_behavior=freshness_behavior,
        transformation_loss=transformation_loss,
        failure_behavior=failure_behavior,
        availability=ComponentAvailability.AVAILABLE,
        claim_boundary=claim_boundary,
    )


def reference_component_registry() -> InteroperabilityComponentRegistry:
    """Return the immutable first-party planning catalog without running a component."""

    components = (
        _component(
            "component:vstd1-independent-auditor",
            "VSTD-1 satisfiability and grounding auditor",
            ComponentKind.CONSTRAINT,
            "verifier.core.checker:IndependentAuditor.audit_claim_derivation",
            "vstd-1-sat-grounding",
            "Verifier Standard bundled Python auditor",
            ("Boolean formula", "recorded grounding graph"),
            ("VSTD1-CHECKER-REPORT",),
            ("typed-python-arguments-unversioned",),
            ("IndependentAuditReport",),
            ("VERIFIED", "FALSIFIED", "INDETERMINATE"),
            ("mechanism:vstd1-sat-grounding-audit",),
            (InteractionMode.STATIC,),
            domain_tags=("constraint", "grounding", "reference"),
            freshness_behavior="The report reflects only the arguments supplied to one call.",
            transformation_loss="No versioned native input schema exists for the typed call arguments.",
            failure_behavior="Formula disagreement and ungrounded structure remain falsified or indeterminate.",
            claim_boundary="A planned match does not run the auditor or demonstrate actor, implementation, or runtime independence.",
        ),
        _component(
            "component:generic-run-validator",
            "VSTD-1 generic-run receipt validator",
            ComponentKind.VERIFIER,
            "verifier.core.run_validation:validate_run_receipt",
            "generic-run",
            "Verifier Standard generic-run profile",
            ("generic computational run receipt",),
            ("VSTD-1", "generic_computational_run"),
            ("VSTD-1 generic-run JavaScript Object Notation receipt",),
            ("process exit status", "diagnostic output"),
            ("PASS", "FAIL"),
            ("mechanism:generic-run-receipt-validation",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-1",),
            domain_tags=("computation", "receipt", "reference"),
            freshness_behavior="Validation reads the supplied stored receipt and currently reachable artifacts.",
            transformation_loss="Diagnostics are not a new receipt and do not replay the declared command.",
            failure_behavior="Malformed structure, digest mismatch, or missing bound artifacts fail validation.",
            claim_boundary="A planned match does not run validation or establish command correctness, reproduction, or conformance.",
        ),
        _component(
            "component:platform-run-comparator",
            "Bounded operating-system result comparator",
            ComponentKind.COMPARATOR,
            "verifier.core.platform_comparison:compare_platform_run_receipts",
            "platform-comparison",
            "Verifier Standard platform comparison diagnostic",
            ("set of generic-run receipts",),
            ("VSTD-PLATFORM-COMPARISON-0.1",),
            ("VSTD-1 generic-run receipt set",),
            ("PlatformComparisonResult",),
            ("PASS", "CONFLICTED", "NOT_ESTABLISHED", "INVALID"),
            ("mechanism:platform-run-comparison",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-1",),
            domain_tags=("cross-platform", "diagnostic", "reference"),
            freshness_behavior="Every comparison is recomputed from the supplied receipt set.",
            transformation_loss="The diagnostic projects only explicitly declared result surfaces.",
            failure_behavior="Missing coverage, incompatibility, disagreement, and invalidity remain distinct.",
            claim_boundary="A planned match does not run comparison or establish universal portability or native-execution attestation.",
        ),
        _component(
            "component:vstd2-geometry-loader",
            "Strict VSTD-2 geometry loader and semantic validator",
            ComponentKind.VERIFIER,
            "verifier.core.geometry_io:load_verification_geometry",
            "vstd-2-geometry",
            "Verifier Standard verification geometry",
            ("VSTD-2 geometry document",),
            ("VSTD-2",),
            ("VSTD-2 JavaScript Object Notation document",),
            ("typed VerificationGeometry",),
            (),
            ("mechanism:vstd2-geometry-validation",),
            (InteractionMode.STATIC,),
            accepted_schema_ids=("VSTD-2",),
            domain_tags=("geometry", "reference", "surface"),
            freshness_behavior="The loader validates the exact supplied mapping or current file bytes.",
            transformation_loss="Integral JSON Schema numbers are normalized to Python integers; source formatting is not retained.",
            failure_behavior="Unknown fields, invalid types, and broken geometry references raise GeometryLoadError.",
            claim_boundary="A planned match does not run loading or establish that the modeled surface is complete in the real world.",
        ),
        _component(
            "component:vstd3-receipt-validator",
            "VSTD-3 hardware receipt validator",
            ComponentKind.VERIFIER,
            "verifier.hardware.validation:validate_vstd3_receipt",
            "vstd-3-hardware",
            "Verifier Standard substrate-accountability model",
            ("VSTD-3 hardware receipt",),
            ("VSTD-3.0",),
            ("typed VSTD3Receipt",),
            ("ReceiptValidation",),
            ("PASS", "FAIL", "UNKNOWN"),
            ("mechanism:vstd3-hardware-receipt-validation",),
            (InteractionMode.OFFLINE_REPLAY,),
            domain_tags=("hardware", "receipt", "reference"),
            freshness_behavior="Freshness is evaluated from receipt timestamps, nonces, and supplied continuity evidence.",
            transformation_loss="Host inventory and normalized vendor fields do not become device attestation.",
            failure_behavior="Missing trust roots or incomplete evidence remain failed or unknown under the profile rules.",
            claim_boundary="A planned match does not run validation or establish production vendor attestation or physical-device identity.",
        ),
        _component(
            "component:vstd4-grounded-certificate-kernel",
            "VSTD-4 grounded decision certificate kernel",
            ComponentKind.CONSTRAINT,
            "verifier.core.kernel:check",
            "vstd-4-evidence-bound",
            "Verifier Standard grounded certificate kernel",
            ("grounded decision certificate",),
            ("VSTD4-GDC-1",),
            ("DecisionCertificate", "optional ClaimBinding"),
            ("KernelResult",),
            ("ACCEPTED", "REJECTED", "REFUSED"),
            ("mechanism:vstd4-grounded-certificate-check",),
            (InteractionMode.STATIC,),
            domain_tags=("certificate", "constraint", "reference"),
            freshness_behavior="The kernel checks one supplied certificate and optional binding.",
            transformation_loss="The certificate proves only its encoded and grounded finite proposition.",
            failure_behavior="Malformed, ungrounded, or invalid derivations are rejected.",
            claim_boundary="A planned match does not run the kernel or establish that the encoded proposition captures the world correctly.",
        ),
        _component(
            "component:vstd4-refutation-producer",
            "Bounded VSTD-4 refutation proof producer",
            ComponentKind.PROVER,
            "verifier.core.refutation:ProofProducingDPLL.solve",
            "vstd-4-evidence-bound",
            "Verifier Standard bounded refutation producer",
            ("Boolean formula",),
            ("VSTD4-RUP-1",),
            ("typed conjunctive-normal-form clauses", "declared proof bounds"),
            ("ProofSearchResult", "optional RefutationCertificate"),
            ("SAT", "UNSAT", "UNKNOWN"),
            ("mechanism:vstd4-refutation-proof-production",),
            (InteractionMode.STATIC,),
            supported_relations=("PRODUCES_CHECKABLE_REFUTATION",),
            domain_tags=("certificate", "proof", "reference"),
            freshness_behavior="The producer searches from the supplied formula under the declared bounds.",
            transformation_loss="A bound-exceeded result carries no proof and remains UNKNOWN.",
            failure_behavior="Proof or decision bounds terminate search as UNKNOWN rather than a verdict.",
            claim_boundary="A planned match does not run proof search or establish that a formula encodes the intended real-world proposition.",
        ),
        _component(
            "component:vstd4-refutation-checker",
            "VSTD-4 reverse-unit-propagation proof checker",
            ComponentKind.CHECKER,
            "verifier.core.refutation:RefutationChecker.check",
            "vstd-4-evidence-bound",
            "Verifier Standard bounded refutation checker",
            ("Boolean formula", "refutation certificate"),
            ("VSTD4-RUP-1",),
            ("typed conjunctive-normal-form clauses", "RefutationCertificate"),
            ("RefutationCheckResult",),
            ("ACCEPTED", "REJECTED"),
            ("mechanism:vstd4-refutation-proof-check",),
            (InteractionMode.STATIC,),
            supported_relations=("PRODUCES_CHECKABLE_REFUTATION",),
            domain_tags=("certificate", "checker", "reference"),
            freshness_behavior="The checker evaluates the supplied formula and proof without re-solving.",
            transformation_loss="Acceptance is limited to reverse-unit-propagation validity of the supplied proof.",
            failure_behavior="A malformed, truncated, or non-implied proof step is rejected.",
            claim_boundary="A planned match does not run proof checking or establish formula grounding, actor independence, or external truth.",
        ),
        _component(
            "component:vstd4-evidence-rechecker",
            "VSTD-4 evidence-bound receipt rechecker",
            ComponentKind.VERIFIER,
            "verifier.core.depth:recheck_evidence_bound_vstd4_receipt",
            "vstd-4-evidence-bound",
            "Verifier Standard evidence-bound VSTD-4 profile",
            ("VSTD-4 evidence-bound receipt",),
            ("VSTD-4", "EVIDENCE_BOUND"),
            ("VSTD-4 receipt", "EvidenceStore", "mechanism registry"),
            ("EvidenceBoundDepthResult",),
            ("ESTABLISHED", "NOT_ESTABLISHED"),
            ("mechanism:vstd4-evidence-bound-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-4",),
            domain_tags=("evidence", "receipt", "reference"),
            freshness_behavior="Recheck rehashes evidence and reruns registered mechanisms at call time.",
            transformation_loss="The result is bounded to registered mechanisms, roots, and declared resource limits.",
            failure_behavior="Missing evidence, mechanism drift, or kernel failure prevents establishment.",
            claim_boundary="A planned match does not run recheck or establish correctness beyond the bound mechanisms and trust roots.",
        ),
        _component(
            "component:vstd5-witness-rechecker",
            "VSTD-5 witness corroboration rechecker",
            ComponentKind.VERIFIER,
            "verifier.core.witness:recheck_vstd5_receipt",
            "vstd-5-witness",
            "Verifier Standard witness corroboration profile",
            ("VSTD-5 witness receipt",),
            ("VSTD-5",),
            ("VSTD-5 receipt", "EvidenceStore", "mechanism registry"),
            ("WitnessCorroborationResult",),
            ("CORROBORATED", "REFUTED", "UNKNOWN", "CONFLICTED"),
            ("mechanism:vstd5-witness-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-5",),
            domain_tags=("corroboration", "receipt", "witness"),
            freshness_behavior="Recheck repeats every bound witness mechanism against the supplied evidence store.",
            transformation_loss="Normalized dimensions retain native disagreement but cannot create independent witnesses.",
            failure_behavior="Contradiction and unresolved independence remain conflicted or unknown.",
            claim_boundary="A planned match does not run recheck, create an external witness, or establish independence by agreement.",
        ),
        _component(
            "component:graph-topology-analyzer",
            "Experimental exact-graph-bound topology analyzer",
            ComponentKind.CONSTRAINT,
            "verifier.interoperability.graph_topology:analyze_graph_topology",
            "vstd-graph",
            "Verifier Standard experimental graph topology interpretation",
            ("recorded provenance hypergraph", "exact graph and port-bound topology contract"),
            ("VSTD-GRAPH-TOPOLOGY-EXPERIMENTAL-0.1",),
            ("typed ProvenanceHypergraph", "typed GraphTopologyContract", "max_assignments bound"),
            ("GraphTopologyReport",),
            ("CONSISTENT", "CONFLICTED", "NOT_ESTABLISHED", "INVALID"),
            ("mechanism:graph-topology-analysis",),
            (InteractionMode.STATIC,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            emitted_schema_ids=("VSTD-GRAPH-TOPOLOGY-REPORT-EXPERIMENTAL-0.1",),
            supported_relations=("relation:graph-topology",),
            domain_tags=("constraint", "experimental", "graph", "topology"),
            freshness_behavior="Analysis binds the exact supplied graph and selected ports, contract, and assignment bound at call time.",
            transformation_loss="Stored contracts are loaded separately; this callable accepts typed objects, not serialized input. Simultaneous classical Boolean equations and temporal offsets per declared clock and unit do not reinterpret provenance as physical causality.",
            failure_behavior="Results remain separate facets with no aggregate verdict. Malformed bindings are invalid; unsupported or incomplete analysis remains NOT_ESTABLISHED. Boolean analysis is bounded to 12 variables, 128 equations, and at most 4096 assignments.",
            claim_boundary="A planned match does not execute the analyzer, establish physical causality, grant mechanism-earned forward artifact support (TRUST), or confer execution authority.",
        ),
        _component(
            "component:composed-untraversability-analyzer",
            "Experimental composed-graph untraversability analyzer",
            ComponentKind.CONSTRAINT,
            "verifier.interoperability.untraversable:analyze_untraversability",
            "vstd-graph",
            "Verifier Standard experimental confidentiality-of-awareness analysis",
            (
                "recorded provenance hypergraph",
                "observer-relative higher-order interface contract",
                "evidence-bound inference rules",
            ),
            ("VSTD-UNTRAVERSABLE-EXPERIMENTAL-0.1",),
            (
                "typed ProvenanceHypergraph",
                "typed UntraversableContract",
                "VerificationSession",
            ),
            ("UntraversabilityReport",),
            ("MATCH", "FAIL", "UNKNOWN", "CONFLICTED"),
            ("mechanism:composed-untraversability-analysis",),
            (InteractionMode.STATIC, InteractionMode.OFFLINE_REPLAY),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            emitted_schema_ids=(
                "VSTD-UNTRAVERSABLE-REPORT-EXPERIMENTAL-0.1",
            ),
            supported_relations=("relation:composed-untraversability",),
            domain_tags=(
                "confidentiality-of-awareness",
                "experimental",
                "graph",
                "inference",
            ),
            freshness_behavior="Analysis reruns registered evidence mechanisms and finite closure for the exact graph, observer, interfaces, transcript, interval, capabilities, and resource coordinate.",
            transformation_loss="Facts use caller-selected identifiers and commitments; identifiers and relationship metadata may themselves disclose. Raw protected contents and unmodeled inference or side-channel semantics are outside the report.",
            failure_behavior="A supported hyperpath is FAIL; conflicting relevant rule evidence remains CONFLICTED; missing evidence, incomplete coverage, unsupported semantics, or exhausted bounds remain UNKNOWN. Evidence ceilings cover unique payloads, not repeated mechanism work.",
            claim_boundary="A planned match does not execute the analyzer. MATCH establishes only bounded closure of the declared complete model and grants no universal confidentiality, authorization, identity, intent, conformance, or execution authority.",
        ),
        _component(
            "component:vstd-graph-receipt-validator",
            "VSTD-Graph receipt validator",
            ComponentKind.VERIFIER,
            "verifier.data.receipt:validate_data_receipt",
            "vstd-graph",
            "Verifier Standard provenance hypergraph receipt",
            ("VSTD-Graph-1 receipt",),
            ("VSTD-DATA-0.1",),
            ("VSTD-DATA-0.1 JavaScript Object Notation receipt",),
            ("process exit status", "diagnostic output"),
            ("PASS", "FAIL"),
            ("mechanism:vstd-graph-receipt-validation",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-DATA-0.1",),
            domain_tags=("graph", "provenance", "receipt"),
            freshness_behavior="Validation reads the supplied stored graph receipt and its recorded state.",
            transformation_loss="Recorded reachability does not represent omitted lineage or real-world causality.",
            failure_behavior="Malformed shape, digest mismatch, and invalid recorded graph structure fail validation.",
            claim_boundary="A planned match does not run validation or establish that recorded lineage is complete or causal.",
        ),
        _component(
            "component:vstd-graph-level-rechecker",
            "Evidence-bound VSTD-Graph profile rechecker",
            ComponentKind.VERIFIER,
            "verifier.data.graph_level:recheck_evidence_bound_graph_level_record",
            "vstd-graph",
            "Verifier Standard evidence-bound graph profiles",
            ("evidence-bound graph-level record",),
            ("VSTD-DATA-0.1", "MECHANISM_EVALUATED"),
            ("graph-level record", "EvidenceStore", "mechanism registry"),
            ("EvidenceBoundGraphLevelResult",),
            ("ESTABLISHED", "NOT_ESTABLISHED"),
            ("mechanism:vstd-graph-level-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            domain_tags=("evidence", "graph", "reference"),
            freshness_behavior="Recheck reruns bound object and edge mechanisms over the supplied collection.",
            transformation_loss="The result is limited to the declared, deduplicated graph collection.",
            failure_behavior="Missing evidence or any nonpassing required mechanism prevents establishment.",
            claim_boundary="A planned match does not run recheck or establish hidden members, omitted edges, or complete causality.",
        ),
        _component(
            "component:vstd-graph-assurance-rechecker",
            "VSTD-Graph assurance-log rechecker",
            ComponentKind.VERIFIER,
            "verifier.data.assurance:recheck_assurance_log",
            "vstd-graph-assurance",
            "Verifier Standard assurance event log",
            ("VSTD-Graph assurance log",),
            ("VSTD-GRAPH-ASSURANCE-1",),
            ("assurance log", "EvidenceStore", "mechanism registry"),
            ("AssuranceLedger",),
            (),
            ("mechanism:vstd-graph-assurance-log-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-GRAPH-ASSURANCE-1",),
            domain_tags=("assurance", "graph", "replay"),
            freshness_behavior="Replay rehashes the historical graph and reruns evidence-bound event mechanisms.",
            transformation_loss="Graph propagation remains bounded diagnostic support and not universal assurance.",
            failure_behavior="The callable returns a replayed AssuranceLedger or raises AssuranceFlowError on hash-chain, evidence, or mechanism mismatch; it emits no aggregate status vocabulary.",
            claim_boundary="A planned match does not run replay or convert graph proximity into correctness, responsibility, or guilt.",
        ),
        _component(
            "component:artifact-bundle-verifier",
            "Artifact freeze and seal verifier",
            ComponentKind.VERIFIER,
            "verifier.artifact_control:verify_frozen_artifact",
            "artifact-control",
            "Verifier Standard artifact control",
            ("frozen artifact bundle",),
            ("VSTD-ARTIFACT-FREEZE-1", "VSTD-ARTIFACT-SEAL-1"),
            ("artifact-control bundle path", "optional expected anchors"),
            ("ArtifactVerification",),
            ("FAIL", "CONFLICTED", "SEALED", "FROZEN_UNSEALED", "NOT_ESTABLISHED"),
            ("mechanism:artifact-bundle-verification",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-ARTIFACT-FREEZE-1", "VSTD-ARTIFACT-SEAL-1"),
            optional_dependencies=("cryptography for seal verification",),
            domain_tags=("artifact", "integrity", "reference"),
            freshness_behavior="Verification re-reads current bundle paths and bytes on every call.",
            transformation_loss="Byte identity does not establish semantic correctness, custody, or trusted time.",
            failure_behavior="Byte, guard, seal, or expected-anchor mismatch cannot produce a clean state.",
            claim_boundary="A planned match does not run artifact verification or establish semantic correctness, custody, or encryption.",
        ),
        _component(
            "component:artifact-network-authority-composition-assessor",
            "Experimental finite authority-composition assessor",
            ComponentKind.CHECKER,
            "verifier.interoperability.authority_composition:assess_authority_composition",
            "artifact-network",
            "Verifier Standard experimental finite authority composition",
            ("exact finite authority-composition declaration", "digest-keyed commit and authority-model bytes"),
            ("VSTD-FINITE-AUTHORITY-COMPOSITION-PROFILE-0.1", "ASYNCHRONOUS_INTERLEAVING", _AUTHORITY_COMPOSITION_PROFILE_DIGEST),
            ("VSTD-FINITE-AUTHORITY-COMPOSITION-0.1 canonical bytes", "digest-keyed immutable evidence mapping"),
            ("VSTD-FINITE-AUTHORITY-COMPOSITION-RESULT-0.1 decoded object",),
            ("BOUND", "MATCHED", "MISMATCH", "PRESERVED", "VIOLATED", "INVALID", "UNKNOWN"),
            ("mechanism:finite-authority-composition-assessment",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("VSTD-FINITE-AUTHORITY-COMPOSITION-0.1",),
            emitted_schema_ids=("VSTD-FINITE-AUTHORITY-COMPOSITION-RESULT-0.1",),
            supported_relations=("relation:assesses-finite-authority-composition",),
            domain_tags=("artifact", "authority", "composition", "experimental"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_AUTHORITY_COMPOSITION_PROFILE_DIGEST}",),
            freshness_behavior="Each call binds exact member and composite commits and model selections, then enumerates the bounded reachable asynchronous-interleaving product from supplied bytes without storage reads.",
            transformation_loss="The compiled inert profile identifies the declared rule, not implementation or execution identity. The retained FINITE_AUTHORITY_COMPOSITION.md specification bounds the model translation; the evidence mapping has no standalone serialized schema.",
            failure_behavior="Malformed binding remains INVALID; missing evidence, unsupported profiles and exceeded bounds remain UNKNOWN; definite correspondence mismatches and reachable authority removals remain separate negative results.",
            claim_boundary="A planned match neither runs assessment nor establishes native input validity. Finite correspondence does not establish source grounding, self-derivation, stronger completeness, runtime behavior, general agency, or a six-axis silo-status upgrade.",
        ),
        _component(
            "component:artifact-network-composition-declaration-decoder",
            "Experimental strict silo-composition declaration decoder",
            ComponentKind.ADAPTER,
            "verifier.interoperability.network:SiloComposition.from_dict",
            "artifact-network",
            "Verifier Standard experimental verification-artifact network",
            ("exact silo-composition declaration",),
            ("VSTD-SILO-COMPOSITION-0.1",),
            ("VSTD-SILO-COMPOSITION-0.1 decoded object",),
            ("SiloComposition",),
            (),
            ("mechanism:artifact-network-composition-declaration-decode",),
            (InteractionMode.STATIC,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("VSTD-SILO-COMPOSITION-0.1",),
            supported_relations=("relation:decodes-silo-composition-declaration",),
            domain_tags=("artifact", "composition", "experimental", "network"),
            freshness_behavior="Each call strictly reconstructs the supplied declaration and rejects noncanonical member order, duplicate members, unknown fields, and malformed digests.",
            transformation_loss="Decoding retains exact member and optional composite commit digests but resolves no commit bytes or graph edges.",
            failure_behavior="Malformed or noncanonical declarations raise NetworkError rather than yielding a partial declaration.",
            claim_boundary="A planned match does not run declaration decoding, resolve members, check general graph edges, establish TypeScript support, or grant composition admissibility.",
        ),
        _component(
            "component:artifact-network-composition-receipt-builder",
            "Experimental silo-composition assessment receipt builder",
            ComponentKind.COLLECTOR,
            "verifier.interoperability.network:build_silo_composition_assessment_receipt",
            "artifact-network",
            "Verifier Standard experimental verification-artifact network",
            ("typed silo-composition declaration", "resolved member silos", "optional resolved composite silo"),
            ("VSTD-SILO-COMPOSITION-MECHANISM-0.1",),
            ("SiloComposition", "ordered SiloCommit and ContentAddressedStore pairs"),
            ("SiloCompositionAssessmentReceipt",),
            ("ADMISSIBLE", "NOT_ADMISSIBLE"),
            ("mechanism:artifact-network-composition-receipt-construction",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            emitted_schema_ids=("VSTD-SILO-COMPOSITION-ASSESSMENT-RECEIPT-0.1",),
            supported_relations=("relation:constructs-silo-composition-assessment-receipt",),
            domain_tags=("artifact", "composition", "experimental", "receipt"),
            freshness_behavior="Each call recomputes member and optional composite silo assessments from the supplied current content-addressed stores before binding the declaration, mechanism, nested receipts, and result.",
            transformation_loss="The receipt covers only the exact declared silo composition and reference mechanism; it is not a general graph-edge assessment.",
            failure_behavior="Unresolved, substituted, duplicate, or declaration-mismatched members raise NetworkError; nonadmissible assessed states remain NOT_ADMISSIBLE.",
            claim_boundary="A planned match does not run receipt construction, establish an independently implemented checker, check general graph edges, establish TypeScript support, or prove artifact truth.",
        ),
        _component(
            "component:artifact-network-composition-receipt-rechecker",
            "Experimental silo-composition assessment receipt rechecker",
            ComponentKind.VERIFIER,
            "verifier.interoperability.network:recheck_silo_composition_assessment_receipt",
            "artifact-network",
            "Verifier Standard experimental verification-artifact network",
            ("silo-composition assessment receipt", "exact declaration and resolved silos"),
            ("VSTD-SILO-COMPOSITION-ASSESSMENT-RECEIPT-0.1",),
            ("SiloComposition", "SiloCompositionAssessmentReceipt or decoded receipt object", "ordered SiloCommit and ContentAddressedStore pairs"),
            ("None on exact independent recomputation",),
            (),
            ("mechanism:artifact-network-composition-receipt-independent-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("VSTD-SILO-COMPOSITION-ASSESSMENT-RECEIPT-0.1",),
            supported_relations=("relation:rechecks-silo-composition-assessment-receipt",),
            domain_tags=("artifact", "composition", "experimental", "receipt"),
            freshness_behavior="Each call independently recomputes the complete reference receipt from the supplied declaration, current stores, and exact member and optional composite commits, then compares canonical bytes.",
            transformation_loss="Equality establishes agreement with the same reference mechanism at the supplied coordinate, not implementation independence or a general graph-edge result.",
            failure_behavior="Malformed receipts, changed evidence, declaration drift, mechanism drift, or any canonical mismatch raise NetworkError.",
            claim_boundary="A planned match does not run receipt rechecking, supply an independent implementation, check general graph edges, establish TypeScript support, or extend the receipt beyond its declared silos.",
        ),
        _component(
            "component:artifact-network-proposition-transfer-assessor",
            "Experimental finite-set proposition-transfer assessor",
            ComponentKind.CHECKER,
            "verifier.interoperability.proposition_transfer:assess_transfer",
            "artifact-network",
            "Verifier Standard experimental direct finite-set transfer",
            ("exact proposition-transfer declaration", "digest-keyed commit and artifact bytes"),
            ("VSTD-PROPOSITION-TRANSFER-RULE-0.1", "canonical_finite_set_union_v1", _TRANSFER_PROFILE_DIGEST),
            ("VSTD-PROPOSITION-TRANSFER-0.1 canonical bytes", "digest-keyed immutable evidence mapping"),
            ("VSTD-PROPOSITION-TRANSFER-ASSESSMENT-0.1 decoded object",),
            ("PASS", "FAIL", "INVALID", "UNKNOWN", "SUPPORTED", "NOT_ESTABLISHED"),
            ("mechanism:artifact-network-proposition-transfer-assessment",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("VSTD-PROPOSITION-TRANSFER-0.1",),
            emitted_schema_ids=("VSTD-PROPOSITION-TRANSFER-ASSESSMENT-0.1",),
            supported_relations=("relation:assesses-proposition-transfer",),
            domain_tags=("artifact", "experimental", "finite-set", "proposition-transfer"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_TRANSFER_PROFILE_DIGEST}",),
            freshness_behavior="Every call rechecks exact commit, census, artifact and context coordinates from retained bounded input bytes; it performs no storage reads.",
            transformation_loss=f"The compiled semantic profile is mirrored at {_TRANSFER_PROFILE_PATH}; profile identity is not implementation or execution identity. Native evidence mappings have no standalone serialized schema.",
            failure_behavior="Malformed declarations raise PropositionTransferError; unsupported rules remain UNKNOWN, missing evidence does not erase known negatives, and a true target does not repair a failed transfer.",
            claim_boundary="A planned mechanism match does not establish rule-profile compatibility or run assessment. Native results do not establish execution identity, authority, graph-wide deduction, six-axis silo completeness, or universal truth.",
        ),
        _component(
            "component:artifact-network-proposition-transfer-rechecker",
            "Experimental finite-set proposition-transfer receipt rechecker",
            ComponentKind.CHECKER,
            "verifier.interoperability.proposition_transfer:recheck_transfer_receipt",
            "artifact-network",
            "Verifier Standard experimental direct finite-set transfer",
            ("exact proposition-transfer declaration and receipt", "digest-keyed commit and artifact bytes"),
            ("VSTD-PROPOSITION-TRANSFER-RULE-0.1", "canonical_finite_set_union_v1", _TRANSFER_PROFILE_DIGEST),
            ("VSTD-PROPOSITION-TRANSFER-0.1 canonical bytes", "VSTD-PROPOSITION-TRANSFER-RECEIPT-0.1 canonical bytes", "digest-keyed immutable evidence mapping"),
            ("VSTD-PROPOSITION-TRANSFER-ASSESSMENT-0.1 decoded object",),
            ("PASS", "FAIL", "INVALID", "UNKNOWN", "SUPPORTED", "NOT_ESTABLISHED"),
            ("mechanism:artifact-network-proposition-transfer-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("VSTD-PROPOSITION-TRANSFER-0.1", "VSTD-PROPOSITION-TRANSFER-RECEIPT-0.1"),
            emitted_schema_ids=("VSTD-PROPOSITION-TRANSFER-ASSESSMENT-0.1",),
            supported_relations=("relation:rechecks-proposition-transfer-receipt",),
            domain_tags=("artifact", "experimental", "finite-set", "proposition-transfer", "receipt"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_TRANSFER_PROFILE_DIGEST}",),
            freshness_behavior="Every call rebuilds the complete semantic receipt using current supplied bounded evidence and compares exact canonical bytes, including negative and unknown fields.",
            transformation_loss=f"The compiled semantic profile is mirrored at {_TRANSFER_PROFILE_PATH}; replay equality is not independent implementation or execution identity. Native evidence mappings have no standalone serialized schema.",
            failure_behavior="Malformed records or wrong declaration/profile binding raise PropositionTransferError; unequal current replay raises TRANSFER_NOT_REPRODUCED, not a forgery or negation verdict. Reproduced FAIL and UNKNOWN results remain negative or unknown.",
            claim_boundary="A planned mechanism match does not establish rule-profile compatibility or run rechecking. Receipt equality does not establish execution identity, authority, graph-wide deduction, six-axis silo completeness, or universal truth.",
        ),
        _component(
            "component:artifact-network-typed-formation-producer",
            "Experimental finite typed-formation certificate producer",
            ComponentKind.PROVER,
            "verifier.interoperability.formation_producer:produce_formation_certificate",
            "artifact-network",
            "Verifier Standard experimental finite typed formation",
            ("finite typed-formation subject",),
            ("VSTD-TYPED-FORMATION-PROFILE-0.1", _FORMATION_PROFILE_DIGEST),
            ("VSTD-TYPED-FORMATION-0.1 canonical immutable subject bytes",),
            ("VSTD-TYPED-FORMATION-CERTIFICATE-0.1 canonical immutable certificate bytes",),
            (),
            ("mechanism:typed-formation-certificate-production",),
            (InteractionMode.STATIC,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("VSTD-TYPED-FORMATION-0.1",),
            emitted_schema_ids=("VSTD-TYPED-FORMATION-CERTIFICATE-0.1",),
            supported_relations=("relation:produces-typed-formation-certificate",),
            domain_tags=("artifact", "certificate", "experimental", "typed-formation"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_FORMATION_PROFILE_DIGEST}",),
            freshness_behavior="Each call constructs a certificate for exactly one supplied finite subject and the compiled profile; it does not call the checker.",
            transformation_loss=f"The inert profile is retained at {_FORMATION_PROFILE_PATH}; src/verifier/specifications/TYPED_FORMATION.md and src/verifier/schemas/vstd-typed-formation-0.1.schema.json define the bounded contract. Certificate production emits no acceptance verdict and does not discharge residual source obligations.",
            failure_behavior="Malformed syntax or incompatible formation raises FormationError; unsupported schema/profile raises UnsupportedFormation and exceeded finite bounds raise FormationLimitError. No partial certificate is returned.",
            claim_boundary=_FORMATION_BOUNDARY,
        ),
        _component(
            "component:artifact-network-typed-formation-checker",
            "Experimental finite typed-formation certificate checker",
            ComponentKind.CHECKER,
            "verifier.interoperability.formation_checker:check_formation",
            "artifact-network",
            "Verifier Standard experimental finite typed formation",
            ("finite typed-formation subject", "exact formation certificate"),
            ("VSTD-TYPED-FORMATION-PROFILE-0.1", _FORMATION_PROFILE_DIGEST),
            ("VSTD-TYPED-FORMATION-0.1 canonical immutable subject bytes", "VSTD-TYPED-FORMATION-CERTIFICATE-0.1 canonical immutable certificate bytes"),
            ("typed-formation report mapping (unversioned)",),
            ("CHECKED", "INVALID", "UNKNOWN"),
            ("mechanism:typed-formation-certificate-check",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("VSTD-TYPED-FORMATION-0.1", "VSTD-TYPED-FORMATION-CERTIFICATE-0.1"),
            supported_relations=("relation:checks-typed-formation-certificate",),
            domain_tags=("artifact", "certificate", "experimental", "typed-formation"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_FORMATION_PROFILE_DIGEST}",),
            freshness_behavior="Every call independently reconstructs finite typed nodes and paths from the exact supplied subject and certificate bytes; no producer, stored verdict or external artifact is consulted.",
            transformation_loss=f"The inert profile is retained at {_FORMATION_PROFILE_PATH}; profile identity is not implementation identity. The report has no standalone serialized schema, preserves all residual obligations, and distinguishes normalized denotation from exact formation identity.",
            failure_behavior="Known malformed or substituted records, proof steps, types and endpoints yield INVALID; unsupported schema/profile and exceeded resource ceilings yield UNKNOWN. Only a complete bounded check yields CHECKED.",
            claim_boundary=_FORMATION_BOUNDARY,
        ),
        _component(
            "component:artifact-network-typed-formation-receipt-rechecker",
            "Experimental finite-formation receipt rechecker",
            ComponentKind.CHECKER,
            "verifier.interoperability.formation_receipt:recheck_formation_receipt",
            "artifact-network",
            "Verifier Standard experimental finite typed formation",
            ("exact formation selection and receipt", "selected commit and observed census bytes"),
            ("VSTD-TYPED-FORMATION-PROFILE-0.1", _FORMATION_PROFILE_DIGEST),
            ("VSTD-SILO-FORMATION-SELECTION-0.1 canonical immutable selection bytes", "VSTD-SILO-COMMIT-0.1 canonical immutable commit bytes", "VSTD-SILO-FORMATION-RECEIPT-0.1 canonical immutable receipt bytes", "bounded ordinary digest-keyed immutable evidence dictionary"),
            ("retained-silo formation inspection mapping (unversioned)",),
            ("BOUND", "COMPLETE", "INCOMPLETE", "MATCHED", "CHECKED", "INVALID", "UNKNOWN"),
            ("mechanism:typed-formation-receipt-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("VSTD-SILO-COMMIT-0.1", "VSTD-SILO-FORMATION-RECEIPT-0.1", "VSTD-SILO-FORMATION-SELECTION-0.1"),
            supported_relations=("relation:rechecks-typed-formation-receipt",),
            domain_tags=("artifact", "experimental", "receipt", "typed-formation"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_FORMATION_PROFILE_DIGEST}", "EXACT_FORMATION_SELECTION", "OBSERVED_CENSUS_BYTES"),
            freshness_behavior="Every call captures bounded input bytes, reruns formation inspection, reconstructs the observed-evidence-bound receipt and compares its complete canonical bytes. No stored verdict is trusted or submitted code executed.",
            transformation_loss=f"The inert profile is retained at {_FORMATION_PROFILE_PATH}; src/verifier/specifications/FORMATION_RECEIPT.md defines strict selection and observed-evidence binding. The returned inspection has no standalone wire discriminator. Receipt identity is not implementation or execution identity; provider diagnostics are not portable evidence bytes.",
            failure_behavior="Malformed, unsupported, over-budget or mismatched input raises FormationReceiptError. Unequal replay is FORMATION_RECEIPT_NOT_REPRODUCED, not forgery or claim negation. Reproduced INVALID, UNKNOWN and INCOMPLETE remain negative or uncertain results.",
            claim_boundary=_FORMATION_BOUNDARY,
        ),
        _component(
            "component:artifact-network-typed-formation-session-mechanism",
            "Experimental typed-formation native session adapter",
            ComponentKind.ADAPTER,
            "verifier.interoperability.formation_mechanism:FormationPathCertificateMechanism.evaluate",
            "artifact-network",
            "Verifier Standard experimental finite typed formation",
            ("exact evidence-bound formation proposition", "ordered subject and certificate bytes"),
            ("VSTD-TYPED-FORMATION-PROFILE-0.1", "vstd.typed_formation.checked.0.1", _FORMATION_PROFILE_DIGEST),
            ("BoundProposition typed native declaration (unversioned)", "ordered immutable subject/certificate byte pair (unversioned)"),
            ("MechanismDecision with preserved formation_report and residual_obligations (unversioned)",),
            ("PASS", "FAIL", "UNKNOWN"),
            ("vstd.typed_formation.checked.0.1",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            supported_relations=("relation:checks-bound-typed-formation-proposition",),
            domain_tags=("artifact", "certificate", "experimental", "typed-formation"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_FORMATION_PROFILE_DIGEST}", "EXACT_BOUND_PROPOSITION", "DECLARED_CONTEXT_DIGESTS", "EXPLICIT_MECHANISM_INSTANCE"),
            freshness_behavior="This reference names an unbound instance method: explicitly construct FormationPathCertificateMechanism() and invoke its bound evaluate, or register that instance in VerificationSession. Catalog matching never instantiates it. Admitted evaluation requires exact predicate, expected CHECKED, profile, subject and declared context bindings, and rehashes the ordered evidence pair. Early refusals can precede pure checking.",
            transformation_loss=f"The inert profile is retained at {_FORMATION_PROFILE_PATH}; this typed wrapper has no standalone serialized input or result schema. Its implementation digest binds four selected source files plus profile, not loaded code or full dependencies. Ground and agency trust roots remain declared assumptions.",
            failure_behavior="Recognized binding or formation failures yield FAIL only for the exact certificate predicate; unsupported declarations, missing evidence, exhausted bounds and execution failure remain UNKNOWN. Pure checker results and every residual obligation remain separate.",
            claim_boundary=_FORMATION_BOUNDARY,
        ),
        _component(
            "component:artifact-network-transfer-materializer",
            "Experimental artifact-network transfer materializer",
            ComponentKind.ADAPTER,
            "verifier.interoperability.network:materialize_silo_transfer",
            "artifact-network",
            "Verifier Standard experimental verification-artifact network",
            ("bounded signed complete-snapshot silo transfer",),
            ("VSTD-SILO-TRANSFER-0.1",),
            ("canonical transfer bytes or decoded transfer object", "absent destination path"),
            ("VSTD-SILO-EXPORT-0.1 portable manifest", "materialized content-addressed silo"),
            (),
            ("mechanism:artifact-network-transfer-materialization",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("VSTD-SILO-TRANSFER-0.1",),
            emitted_schema_ids=("VSTD-SILO-EXPORT-0.1",),
            optional_dependencies=("cryptography for Ed25519 signature verification",),
            domain_tags=("artifact", "experimental", "interoperability", "network"),
            freshness_behavior="Each call revalidates the supplied transfer bytes and the newly materialized destination tree.",
            transformation_loss="Materialization preserves the selected snapshot bytes but does not preserve a live endpoint, publisher custody, or service history.",
            failure_behavior="Malformed, oversized, incomplete, substituted, noncanonical, or signature-invalid transfers are rejected and cannot leave a successful destination.",
            claim_boundary="A planned match does not run transfer validation, contact a deployed service, establish publisher identity, prove artifact truth, or qualify any untested platform coordinate.",
        ),
        _component(
            "component:provenance-policy-verifier",
            "Recorded provenance policy verifier",
            ComponentKind.POLICY,
            "verifier.data.policy:ProvenancePolicyVerifier",
            "provenance-policy",
            "Verifier Standard provenance policy engine",
            ("recorded provenance hypergraph",),
            ("POL-NO-REVOKED-ANCESTORS", "POL-ALL-ANCESTORS-VALID", "POL-APPROVED-LICENSES"),
            ("typed-ProvenanceHypergraph-unversioned", "target artifact identifier"),
            ("PolicyEvaluationResult",),
            ("VERIFIED", "FALSIFIED"),
            (
                "mechanism:policy-all-ancestors-valid",
                "mechanism:policy-approved-licenses",
                "mechanism:policy-no-revoked-ancestors",
            ),
            (InteractionMode.STATIC,),
            domain_tags=("policy", "provenance", "reference"),
            freshness_behavior="Each policy reads the supplied in-memory recorded graph state.",
            transformation_loss="The typed method arguments have no standalone versioned input schema.",
            failure_behavior="Encoding/direct-computation disagreement raises rather than selecting a convenient result.",
            claim_boundary="A planned match does not run policy verification or establish hidden ancestry, authentic statuses, or legal conclusions.",
        ),
        _component(
            "component:scitt-evidence-consumer",
            "SCITT native-evidence consumer",
            ComponentKind.ADAPTER,
            "verifier.interoperability.scitt.adapter:consume_scitt_evidence",
            "vstd-scitt-composition",
            "Experimental VSTD and SCITT mapping",
            ("normalized native SCITT verifier output",),
            ("vstd-scitt-interop-experimental-0.1",),
            ("ScittRegistrationTemplate", "native verifier result mapping"),
            ("bounded SCITT transparency evidence mapping",),
            ("REGISTERED", "MISSING", "STALE", "CONFLICTED", "REVOKED", "SUPERSEDED", "UNKNOWN", "INVALID"),
            ("mechanism:scitt-native-evidence-consumption",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            domain_tags=("experimental", "software-supply-chain", "transparency"),
            freshness_behavior="The adapter preserves supplied registration time and native freshness state.",
            transformation_loss="The normalized mapping is not a native Concise Binary Object Representation or signature verifier.",
            failure_behavior="Incomplete, mismatched, stale, or contradictory evidence remains non-registered.",
            claim_boundary="A planned match does not run a SCITT verifier or establish registration, payload truth, or VSTD conformance.",
        ),
        _component(
            "component:scitt-result-composer",
            "VSTD and SCITT adjacent-result composer",
            ComponentKind.TRANSLATOR,
            "verifier.interoperability.scitt.adapter:compose_results",
            "vstd-scitt-composition",
            "Experimental VSTD and SCITT mapping",
            ("native VSTD result", "normalized SCITT evidence"),
            ("vstd-scitt-interop-experimental-0.1",),
            ("VstdVerificationEvidence", "ScittVerificationEvidence", "VstdScittPayload"),
            ("CompositionResult",),
            ("PASS", "FAIL", "UNKNOWN", "CONFLICTED"),
            ("mechanism:vstd-scitt-adjacent-composition",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            domain_tags=("composition", "experimental", "software-supply-chain"),
            freshness_behavior="Composition uses only the supplied current native evidence objects.",
            transformation_loss="Composition retains native results but cannot strengthen either source mechanism.",
            failure_behavior="Every nonpassing or mismatched source state is preserved or lowered.",
            claim_boundary="A planned match does not run either native verifier or establish payload truth, safety, or VSTD conformance.",
        ),
    )
    return InteroperabilityComponentRegistry(
        registry_version=REFERENCE_CATALOG_VERSION,
        components=components,
    )


__all__ = [
    "REFERENCE_CATALOG_CLAIM_BOUNDARY",
    "REFERENCE_CATALOG_VERSION",
    "reference_component_registry",
]
