"""Terminology: Davis-Putnam-Logemann-Loveland (DPLL); grounded decision certificate (GDC);
JavaScript Object Notation (JSON); reverse unit propagation (RUP);
Boolean satisfiability problem (SAT); Supply Chain Integrity, Transparency, and Trust (SCITT);
unsatisfiable (UNSAT); Verifier Standard (VSTD).

First-party component inventory for exact, nonexecuting VSTD-2 planning.

``planning_surface_schema_ids`` names the modeled surface schema from which a
component may be considered. ``accepted_schema_ids`` names only explicit native
serialized input schemas; it remains empty for typed or unversioned callables.
Registry construction never imports or executes an implementation entry point.
"""

from __future__ import annotations

from verifier.interoperability.catalog import (
    ComponentAvailability,
    ComponentKind,
    ComponentLifecycle,
    InteractionMode,
    InteroperabilityComponentDescriptor,
    InteroperabilityComponentRegistry,
)


REFERENCE_CATALOG_VERSION = "VSTD-REFERENCE-COMPONENTS-1.0"
REFERENCE_CATALOG_CLAIM_BOUNDARY = (
    "Catalog membership records first-party implementation entry points for exact "
    "planning matches. It does not execute a component, prove runtime availability, "
    "establish native input validity, or grant a VSTD result."
)


def _component(
    component_id: str,
    label: str,
    kind: ComponentKind,
    implementation_ref: str,
    family_id: str,
    native_system: str,
    native_objects: tuple[str, ...],
    native_versions: tuple[str, ...],
    native_inputs: tuple[str, ...],
    native_outputs: tuple[str, ...],
    native_result_vocabulary: tuple[str, ...],
    mechanism_ids: tuple[str, ...],
    interaction_modes: tuple[InteractionMode, ...],
    *,
    lifecycle: ComponentLifecycle = ComponentLifecycle.IMPLEMENTED,
    accepted_schema_ids: tuple[str, ...] = (),
    emitted_schema_ids: tuple[str, ...] = (),
    supported_relations: tuple[str, ...] = (),
    optional_dependencies: tuple[str, ...] = (),
    trust_roots: tuple[str, ...] = (),
    domain_tags: tuple[str, ...] = (),
    freshness_behavior: str,
    transformation_loss: str,
    failure_behavior: str,
    claim_boundary: str,
) -> InteroperabilityComponentDescriptor:
    return InteroperabilityComponentDescriptor(
        component_id=component_id,
        label=label,
        kind=kind,
        lifecycle=lifecycle,
        implementation_ref=implementation_ref,
        accepted_schema_ids=accepted_schema_ids,
        planning_surface_schema_ids=("VSTD-2",),
        verifier_family_ids=(family_id,),
        native_system=native_system,
        native_objects=native_objects,
        native_versions=native_versions,
        native_inputs=native_inputs,
        native_outputs=native_outputs,
        native_result_vocabulary=native_result_vocabulary,
        emitted_schema_ids=emitted_schema_ids,
        supported_relations=supported_relations,
        mechanism_ids=mechanism_ids,
        interaction_modes=interaction_modes,
        domain_tags=domain_tags,
        optional_dependencies=optional_dependencies,
        execution_prerequisites=(
            "EXACT_NATIVE_INPUT",
            "EXACT_IMPLEMENTATION_COORDINATE",
            "RESOURCE_BOUNDS",
        ),
        trust_roots=trust_roots,
        freshness_behavior=freshness_behavior,
        transformation_loss=transformation_loss,
        failure_behavior=failure_behavior,
        availability=ComponentAvailability.AVAILABLE,
        claim_boundary=claim_boundary,
    )


def reference_component_registry() -> InteroperabilityComponentRegistry:
    """Return the immutable first-party planning catalog without running a component."""

    components = (
        _component(
            "component:vstd1-independent-auditor",
            "VSTD-1 satisfiability and grounding auditor",
            ComponentKind.CONSTRAINT,
            "verifier.core.checker:IndependentAuditor.audit_claim_derivation",
            "vstd-1-sat-grounding",
            "Verifier Standard bundled Python auditor",
            ("Boolean formula", "recorded grounding graph"),
            ("VSTD1-CHECKER-REPORT",),
            ("typed-python-arguments-unversioned",),
            ("IndependentAuditReport",),
            ("VERIFIED", "FALSIFIED", "INDETERMINATE"),
            ("mechanism:vstd1-sat-grounding-audit",),
            (InteractionMode.STATIC,),
            domain_tags=("constraint", "grounding", "reference"),
            freshness_behavior="The report reflects only the arguments supplied to one call.",
            transformation_loss="No versioned native input schema exists for the typed call arguments.",
            failure_behavior="Formula disagreement and ungrounded structure remain falsified or indeterminate.",
            claim_boundary="A planned match does not run the auditor or demonstrate actor, implementation, or runtime independence.",
        ),
        _component(
            "component:generic-run-validator",
            "VSTD-1 generic-run receipt validator",
            ComponentKind.VERIFIER,
            "verifier.core.run_validation:validate_run_receipt",
            "generic-run",
            "Verifier Standard generic-run profile",
            ("generic computational run receipt",),
            ("VSTD-1", "generic_computational_run"),
            ("VSTD-1 generic-run JavaScript Object Notation receipt",),
            ("process exit status", "diagnostic output"),
            ("PASS", "FAIL"),
            ("mechanism:generic-run-receipt-validation",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-1",),
            domain_tags=("computation", "receipt", "reference"),
            freshness_behavior="Validation reads the supplied stored receipt and currently reachable artifacts.",
            transformation_loss="Diagnostics are not a new receipt and do not replay the declared command.",
            failure_behavior="Malformed structure, digest mismatch, or missing bound artifacts fail validation.",
            claim_boundary="A planned match does not run validation or establish command correctness, reproduction, or conformance.",
        ),
        _component(
            "component:platform-run-comparator",
            "Bounded operating-system result comparator",
            ComponentKind.COMPARATOR,
            "verifier.core.platform_comparison:compare_platform_run_receipts",
            "platform-comparison",
            "Verifier Standard platform comparison diagnostic",
            ("set of generic-run receipts",),
            ("VSTD-PLATFORM-COMPARISON-0.1",),
            ("VSTD-1 generic-run receipt set",),
            ("PlatformComparisonResult",),
            ("PASS", "CONFLICTED", "NOT_ESTABLISHED", "INVALID"),
            ("mechanism:platform-run-comparison",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-1",),
            domain_tags=("cross-platform", "diagnostic", "reference"),
            freshness_behavior="Every comparison is recomputed from the supplied receipt set.",
            transformation_loss="The diagnostic projects only explicitly declared result surfaces.",
            failure_behavior="Missing coverage, incompatibility, disagreement, and invalidity remain distinct.",
            claim_boundary="A planned match does not run comparison or establish universal portability or native-execution attestation.",
        ),
        _component(
            "component:vstd2-geometry-loader",
            "Strict VSTD-2 geometry loader and semantic validator",
            ComponentKind.VERIFIER,
            "verifier.core.geometry_io:load_verification_geometry",
            "vstd-2-geometry",
            "Verifier Standard verification geometry",
            ("VSTD-2 geometry document",),
            ("VSTD-2",),
            ("VSTD-2 JavaScript Object Notation document",),
            ("typed VerificationGeometry",),
            (),
            ("mechanism:vstd2-geometry-validation",),
            (InteractionMode.STATIC,),
            accepted_schema_ids=("VSTD-2",),
            domain_tags=("geometry", "reference", "surface"),
            freshness_behavior="The loader validates the exact supplied mapping or current file bytes.",
            transformation_loss="Integral JSON Schema numbers are normalized to Python integers; source formatting is not retained.",
            failure_behavior="Unknown fields, invalid types, and broken geometry references raise GeometryLoadError.",
            claim_boundary="A planned match does not run loading or establish that the modeled surface is complete in the real world.",
        ),
        _component(
            "component:vstd3-receipt-validator",
            "VSTD-3 hardware receipt validator",
            ComponentKind.VERIFIER,
            "verifier.hardware.validation:validate_vstd3_receipt",
            "vstd-3-hardware",
            "Verifier Standard substrate-accountability model",
            ("VSTD-3 hardware receipt",),
            ("VSTD-3.0",),
            ("typed VSTD3Receipt",),
            ("ReceiptValidation",),
            ("PASS", "FAIL", "UNKNOWN"),
            ("mechanism:vstd3-hardware-receipt-validation",),
            (InteractionMode.OFFLINE_REPLAY,),
            domain_tags=("hardware", "receipt", "reference"),
            freshness_behavior="Freshness is evaluated from receipt timestamps, nonces, and supplied continuity evidence.",
            transformation_loss="Host inventory and normalized vendor fields do not become device attestation.",
            failure_behavior="Missing trust roots or incomplete evidence remain failed or unknown under the profile rules.",
            claim_boundary="A planned match does not run validation or establish production vendor attestation or physical-device identity.",
        ),
        _component(
            "component:vstd4-grounded-certificate-kernel",
            "VSTD-4 grounded decision certificate kernel",
            ComponentKind.CONSTRAINT,
            "verifier.core.kernel:check",
            "vstd-4-evidence-bound",
            "Verifier Standard grounded certificate kernel",
            ("grounded decision certificate",),
            ("VSTD4-GDC-1",),
            ("DecisionCertificate", "optional ClaimBinding"),
            ("KernelResult",),
            ("ACCEPTED", "REJECTED", "REFUSED"),
            ("mechanism:vstd4-grounded-certificate-check",),
            (InteractionMode.STATIC,),
            domain_tags=("certificate", "constraint", "reference"),
            freshness_behavior="The kernel checks one supplied certificate and optional binding.",
            transformation_loss="The certificate proves only its encoded and grounded finite proposition.",
            failure_behavior="Malformed, ungrounded, or invalid derivations are rejected.",
            claim_boundary="A planned match does not run the kernel or establish that the encoded proposition captures the world correctly.",
        ),
        _component(
            "component:vstd4-refutation-producer",
            "Bounded VSTD-4 refutation proof producer",
            ComponentKind.PROVER,
            "verifier.core.refutation:ProofProducingDPLL.solve",
            "vstd-4-evidence-bound",
            "Verifier Standard bounded refutation producer",
            ("Boolean formula",),
            ("VSTD4-RUP-1",),
            ("typed conjunctive-normal-form clauses", "declared proof bounds"),
            ("ProofSearchResult", "optional RefutationCertificate"),
            ("SAT", "UNSAT", "UNKNOWN"),
            ("mechanism:vstd4-refutation-proof-production",),
            (InteractionMode.STATIC,),
            supported_relations=("PRODUCES_CHECKABLE_REFUTATION",),
            domain_tags=("certificate", "proof", "reference"),
            freshness_behavior="The producer searches from the supplied formula under the declared bounds.",
            transformation_loss="A bound-exceeded result carries no proof and remains UNKNOWN.",
            failure_behavior="Proof or decision bounds terminate search as UNKNOWN rather than a verdict.",
            claim_boundary="A planned match does not run proof search or establish that a formula encodes the intended real-world proposition.",
        ),
        _component(
            "component:vstd4-refutation-checker",
            "VSTD-4 reverse-unit-propagation proof checker",
            ComponentKind.CHECKER,
            "verifier.core.refutation:RefutationChecker.check",
            "vstd-4-evidence-bound",
            "Verifier Standard bounded refutation checker",
            ("Boolean formula", "refutation certificate"),
            ("VSTD4-RUP-1",),
            ("typed conjunctive-normal-form clauses", "RefutationCertificate"),
            ("RefutationCheckResult",),
            ("ACCEPTED", "REJECTED"),
            ("mechanism:vstd4-refutation-proof-check",),
            (InteractionMode.STATIC,),
            supported_relations=("PRODUCES_CHECKABLE_REFUTATION",),
            domain_tags=("certificate", "checker", "reference"),
            freshness_behavior="The checker evaluates the supplied formula and proof without re-solving.",
            transformation_loss="Acceptance is limited to reverse-unit-propagation validity of the supplied proof.",
            failure_behavior="A malformed, truncated, or non-implied proof step is rejected.",
            claim_boundary="A planned match does not run proof checking or establish formula grounding, actor independence, or external truth.",
        ),
        _component(
            "component:vstd4-evidence-rechecker",
            "VSTD-4 evidence-bound receipt rechecker",
            ComponentKind.VERIFIER,
            "verifier.core.depth:recheck_evidence_bound_vstd4_receipt",
            "vstd-4-evidence-bound",
            "Verifier Standard evidence-bound VSTD-4 profile",
            ("VSTD-4 evidence-bound receipt",),
            ("VSTD-4", "EVIDENCE_BOUND"),
            ("VSTD-4 receipt", "EvidenceStore", "mechanism registry"),
            ("EvidenceBoundDepthResult",),
            ("ESTABLISHED", "NOT_ESTABLISHED"),
            ("mechanism:vstd4-evidence-bound-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-4",),
            domain_tags=("evidence", "receipt", "reference"),
            freshness_behavior="Recheck rehashes evidence and reruns registered mechanisms at call time.",
            transformation_loss="The result is bounded to registered mechanisms, roots, and declared resource limits.",
            failure_behavior="Missing evidence, mechanism drift, or kernel failure prevents establishment.",
            claim_boundary="A planned match does not run recheck or establish correctness beyond the bound mechanisms and trust roots.",
        ),
        _component(
            "component:vstd5-witness-rechecker",
            "VSTD-5 witness corroboration rechecker",
            ComponentKind.VERIFIER,
            "verifier.core.witness:recheck_vstd5_receipt",
            "vstd-5-witness",
            "Verifier Standard witness corroboration profile",
            ("VSTD-5 witness receipt",),
            ("VSTD-5",),
            ("VSTD-5 receipt", "EvidenceStore", "mechanism registry"),
            ("WitnessCorroborationResult",),
            ("CORROBORATED", "REFUTED", "UNKNOWN", "CONFLICTED"),
            ("mechanism:vstd5-witness-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-5",),
            domain_tags=("corroboration", "receipt", "witness"),
            freshness_behavior="Recheck repeats every bound witness mechanism against the supplied evidence store.",
            transformation_loss="Normalized dimensions retain native disagreement but cannot create independent witnesses.",
            failure_behavior="Contradiction and unresolved independence remain conflicted or unknown.",
            claim_boundary="A planned match does not run recheck, create an external witness, or establish independence by agreement.",
        ),
        _component(
            "component:graph-topology-analyzer",
            "Experimental exact-graph-bound topology analyzer",
            ComponentKind.CONSTRAINT,
            "verifier.interoperability.graph_topology:analyze_graph_topology",
            "vstd-graph",
            "Verifier Standard experimental graph topology interpretation",
            ("recorded provenance hypergraph", "exact graph and port-bound topology contract"),
            ("VSTD-GRAPH-TOPOLOGY-EXPERIMENTAL-0.1",),
            ("typed ProvenanceHypergraph", "typed GraphTopologyContract", "max_assignments bound"),
            ("GraphTopologyReport",),
            ("CONSISTENT", "CONFLICTED", "NOT_ESTABLISHED", "INVALID"),
            ("mechanism:graph-topology-analysis",),
            (InteractionMode.STATIC,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            emitted_schema_ids=("VSTD-GRAPH-TOPOLOGY-REPORT-EXPERIMENTAL-0.1",),
            supported_relations=("relation:graph-topology",),
            domain_tags=("constraint", "experimental", "graph", "topology"),
            freshness_behavior="Analysis binds the exact supplied graph and selected ports, contract, and assignment bound at call time.",
            transformation_loss="Stored contracts are loaded separately; this callable accepts typed objects, not serialized input. Simultaneous classical Boolean equations and temporal offsets per declared clock and unit do not reinterpret provenance as physical causality.",
            failure_behavior="Results remain separate facets with no aggregate verdict. Malformed bindings are invalid; unsupported or incomplete analysis remains NOT_ESTABLISHED. Boolean analysis is bounded to 12 variables, 128 equations, and at most 4096 assignments.",
            claim_boundary="A planned match does not execute the analyzer, establish physical causality, grant mechanism-earned forward artifact support (TRUST), or confer execution authority.",
        ),
        _component(
            "component:vstd-graph-receipt-validator",
            "VSTD-Graph receipt validator",
            ComponentKind.VERIFIER,
            "verifier.data.receipt:validate_data_receipt",
            "vstd-graph",
            "Verifier Standard provenance hypergraph receipt",
            ("VSTD-Graph-1 receipt",),
            ("VSTD-DATA-0.1",),
            ("VSTD-DATA-0.1 JavaScript Object Notation receipt",),
            ("process exit status", "diagnostic output"),
            ("PASS", "FAIL"),
            ("mechanism:vstd-graph-receipt-validation",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-DATA-0.1",),
            domain_tags=("graph", "provenance", "receipt"),
            freshness_behavior="Validation reads the supplied stored graph receipt and its recorded state.",
            transformation_loss="Recorded reachability does not represent omitted lineage or real-world causality.",
            failure_behavior="Malformed shape, digest mismatch, and invalid recorded graph structure fail validation.",
            claim_boundary="A planned match does not run validation or establish that recorded lineage is complete or causal.",
        ),
        _component(
            "component:vstd-graph-level-rechecker",
            "Evidence-bound VSTD-Graph profile rechecker",
            ComponentKind.VERIFIER,
            "verifier.data.graph_level:recheck_evidence_bound_graph_level_record",
            "vstd-graph",
            "Verifier Standard evidence-bound graph profiles",
            ("evidence-bound graph-level record",),
            ("VSTD-DATA-0.1", "MECHANISM_EVALUATED"),
            ("graph-level record", "EvidenceStore", "mechanism registry"),
            ("EvidenceBoundGraphLevelResult",),
            ("ESTABLISHED", "NOT_ESTABLISHED"),
            ("mechanism:vstd-graph-level-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            domain_tags=("evidence", "graph", "reference"),
            freshness_behavior="Recheck reruns bound object and edge mechanisms over the supplied collection.",
            transformation_loss="The result is limited to the declared, deduplicated graph collection.",
            failure_behavior="Missing evidence or any nonpassing required mechanism prevents establishment.",
            claim_boundary="A planned match does not run recheck or establish hidden members, omitted edges, or complete causality.",
        ),
        _component(
            "component:vstd-graph-assurance-rechecker",
            "VSTD-Graph assurance-log rechecker",
            ComponentKind.VERIFIER,
            "verifier.data.assurance:recheck_assurance_log",
            "vstd-graph-assurance",
            "Verifier Standard assurance event log",
            ("VSTD-Graph assurance log",),
            ("VSTD-GRAPH-ASSURANCE-1",),
            ("assurance log", "EvidenceStore", "mechanism registry"),
            ("AssuranceLedger",),
            (),
            ("mechanism:vstd-graph-assurance-log-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-GRAPH-ASSURANCE-1",),
            domain_tags=("assurance", "graph", "replay"),
            freshness_behavior="Replay rehashes the historical graph and reruns evidence-bound event mechanisms.",
            transformation_loss="Graph propagation remains bounded diagnostic support and not universal assurance.",
            failure_behavior="The callable returns a replayed AssuranceLedger or raises AssuranceFlowError on hash-chain, evidence, or mechanism mismatch; it emits no aggregate status vocabulary.",
            claim_boundary="A planned match does not run replay or convert graph proximity into correctness, responsibility, or guilt.",
        ),
        _component(
            "component:artifact-bundle-verifier",
            "Artifact freeze and seal verifier",
            ComponentKind.VERIFIER,
            "verifier.artifact_control:verify_frozen_artifact",
            "artifact-control",
            "Verifier Standard artifact control",
            ("frozen artifact bundle",),
            ("VSTD-ARTIFACT-FREEZE-1", "VSTD-ARTIFACT-SEAL-1"),
            ("artifact-control bundle path", "optional expected anchors"),
            ("ArtifactVerification",),
            ("FAIL", "CONFLICTED", "SEALED", "FROZEN_UNSEALED", "NOT_ESTABLISHED"),
            ("mechanism:artifact-bundle-verification",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-ARTIFACT-FREEZE-1", "VSTD-ARTIFACT-SEAL-1"),
            optional_dependencies=("cryptography for seal verification",),
            domain_tags=("artifact", "integrity", "reference"),
            freshness_behavior="Verification re-reads current bundle paths and bytes on every call.",
            transformation_loss="Byte identity does not establish semantic correctness, custody, or trusted time.",
            failure_behavior="Byte, guard, seal, or expected-anchor mismatch cannot produce a clean state.",
            claim_boundary="A planned match does not run artifact verification or establish semantic correctness, custody, or encryption.",
        ),
        _component(
            "component:provenance-policy-verifier",
            "Recorded provenance policy verifier",
            ComponentKind.POLICY,
            "verifier.data.policy:ProvenancePolicyVerifier",
            "provenance-policy",
            "Verifier Standard provenance policy engine",
            ("recorded provenance hypergraph",),
            ("POL-NO-REVOKED-ANCESTORS", "POL-ALL-ANCESTORS-VALID", "POL-APPROVED-LICENSES"),
            ("typed-ProvenanceHypergraph-unversioned", "target artifact identifier"),
            ("PolicyEvaluationResult",),
            ("VERIFIED", "FALSIFIED"),
            (
                "mechanism:policy-all-ancestors-valid",
                "mechanism:policy-approved-licenses",
                "mechanism:policy-no-revoked-ancestors",
            ),
            (InteractionMode.STATIC,),
            domain_tags=("policy", "provenance", "reference"),
            freshness_behavior="Each policy reads the supplied in-memory recorded graph state.",
            transformation_loss="The typed method arguments have no standalone versioned input schema.",
            failure_behavior="Encoding/direct-computation disagreement raises rather than selecting a convenient result.",
            claim_boundary="A planned match does not run policy verification or establish hidden ancestry, authentic statuses, or legal conclusions.",
        ),
        _component(
            "component:scitt-evidence-consumer",
            "SCITT native-evidence consumer",
            ComponentKind.ADAPTER,
            "verifier.interoperability.scitt.adapter:consume_scitt_evidence",
            "vstd-scitt-composition",
            "Experimental VSTD and SCITT mapping",
            ("normalized native SCITT verifier output",),
            ("vstd-scitt-interop-experimental-0.1",),
            ("ScittRegistrationTemplate", "native verifier result mapping"),
            ("bounded SCITT transparency evidence mapping",),
            ("REGISTERED", "MISSING", "STALE", "CONFLICTED", "REVOKED", "SUPERSEDED", "UNKNOWN", "INVALID"),
            ("mechanism:scitt-native-evidence-consumption",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            domain_tags=("experimental", "software-supply-chain", "transparency"),
            freshness_behavior="The adapter preserves supplied registration time and native freshness state.",
            transformation_loss="The normalized mapping is not a native Concise Binary Object Representation or signature verifier.",
            failure_behavior="Incomplete, mismatched, stale, or contradictory evidence remains non-registered.",
            claim_boundary="A planned match does not run a SCITT verifier or establish registration, payload truth, or VSTD conformance.",
        ),
        _component(
            "component:scitt-result-composer",
            "VSTD and SCITT adjacent-result composer",
            ComponentKind.TRANSLATOR,
            "verifier.interoperability.scitt.adapter:compose_results",
            "vstd-scitt-composition",
            "Experimental VSTD and SCITT mapping",
            ("native VSTD result", "normalized SCITT evidence"),
            ("vstd-scitt-interop-experimental-0.1",),
            ("VstdVerificationEvidence", "ScittVerificationEvidence", "VstdScittPayload"),
            ("CompositionResult",),
            ("PASS", "FAIL", "UNKNOWN", "CONFLICTED"),
            ("mechanism:vstd-scitt-adjacent-composition",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            domain_tags=("composition", "experimental", "software-supply-chain"),
            freshness_behavior="Composition uses only the supplied current native evidence objects.",
            transformation_loss="Composition retains native results but cannot strengthen either source mechanism.",
            failure_behavior="Every nonpassing or mismatched source state is preserved or lowered.",
            claim_boundary="A planned match does not run either native verifier or establish payload truth, safety, or VSTD conformance.",
        ),
    )
    return InteroperabilityComponentRegistry(
        registry_version=REFERENCE_CATALOG_VERSION,
        components=components,
    )


__all__ = [
    "REFERENCE_CATALOG_CLAIM_BOUNDARY",
    "REFERENCE_CATALOG_VERSION",
    "reference_component_registry",
]
