"""Terminology: Davis-Putnam-Logemann-Loveland (DPLL); grounded decision certificate (GDC);
JavaScript Object Notation (JSON); reverse unit propagation (RUP);
Boolean satisfiability problem (SAT); Supply Chain Integrity, Transparency, and Trust (SCITT);
unsatisfiable (UNSAT); Verifier Standard (VSTD).

First-party component inventory for exact, nonexecuting VSTD-2 planning.

``planning_surface_schema_ids`` names the modeled surface schema from which a
component may be considered. ``accepted_schema_ids`` names only explicit native
serialized input schemas; it remains empty for typed or unversioned callables.
Registry construction never imports or executes an implementation entry point.
"""

from __future__ import annotations

from verifier.interoperability.catalog import (
    ComponentAvailability,
    ComponentKind,
    ComponentLifecycle,
    InteractionMode,
    InteroperabilityComponentDescriptor,
    InteroperabilityComponentRegistry,
)


REFERENCE_CATALOG_VERSION = "verifier-reference-components-1"
REFERENCE_CATALOG_CLAIM_BOUNDARY = (
    "Catalog membership records first-party implementation entry points for exact "
    "planning matches. It does not execute a component, prove runtime availability, "
    "establish native input validity, or grant a VSTD result."
)
_TRANSFER_PROFILE_DIGEST = "sha256:b4cf102904ff248c048d947b093ae3d89deb4ca16582a8f3744ac7f7f3d1a58c"
_TRANSFER_PROFILE_PATH = "src/verifier/profiles/proposition-transfer-rule-1.json"
_FORMATION_PROFILE_DIGEST = "sha256:770f948d29900a63a6ba55f2bbc61bdd18fec1a73769c8e1e524d664c40f6e06"
_FORMATION_PROFILE_PATH = "src/verifier/profiles/typed-formation-1.json"
_AUTHORITY_COMPOSITION_PROFILE_DIGEST = "sha256:cb8a1201a3f0f0d1b156e56ab98964a0a67e41dab487c0158e9c8f52389df719"
_SOURCE_GROUNDING_PROFILE_DIGEST = "sha256:337a71d92fd79d297a22f7577c2de45f23f8cae6470f7e375819d12dcbeb9f75"
_RELATION_BOUNDARY_PROFILE_DIGEST = "sha256:1c127027d5c007216904918586fa1a447c8e8996bb2b6326f523df31a61f9e5b"
_DERIVER_SELF_STATUS_PROFILE_DIGEST = "sha256:ab0398cbc82bc0a2ba9d7efdb73c5afdb64a5b75d6506785e1a683a806a7ea91"
_BOUNDED_COMPLETENESS_PROFILE_DIGEST = "sha256:8c0dab8009847abc17852283424931fdea1d5048859b8d7fcdd1632796eeb79f"
_RUNTIME_AUTHORITY_PROFILE_DIGEST = "sha256:182b39577d507d72a583a4e1dbba21418fc1e480aac48037c01dc3a7bfbe8d25"
_FORMATION_BOUNDARY = (
    "A planned mechanism match does not establish rule-profile compatibility or execution. "
    "Finite formation does not establish source self-derivation, grounding, completeness, "
    "authority axiom agency, historical execution, implementation independence, or a silo-status upgrade."
)


def _component(
    component_id: str,
    label: str,
    kind: ComponentKind,
    implementation_ref: str,
    family_id: str,
    native_system: str,
    native_objects: tuple[str, ...],
    native_versions: tuple[str, ...],
    native_inputs: tuple[str, ...],
    native_outputs: tuple[str, ...],
    native_result_vocabulary: tuple[str, ...],
    mechanism_ids: tuple[str, ...],
    interaction_modes: tuple[InteractionMode, ...],
    *,
    lifecycle: ComponentLifecycle = ComponentLifecycle.IMPLEMENTED,
    accepted_schema_ids: tuple[str, ...] = (),
    emitted_schema_ids: tuple[str, ...] = (),
    supported_relations: tuple[str, ...] = (),
    optional_dependencies: tuple[str, ...] = (),
    trust_roots: tuple[str, ...] = (),
    domain_tags: tuple[str, ...] = (),
    additional_prerequisites: tuple[str, ...] = (),
    freshness_behavior: str,
    transformation_loss: str,
    failure_behavior: str,
    claim_boundary: str,
) -> InteroperabilityComponentDescriptor:
    return InteroperabilityComponentDescriptor(
        component_id=component_id,
        label=label,
        kind=kind,
        lifecycle=lifecycle,
        implementation_ref=implementation_ref,
        accepted_schema_ids=accepted_schema_ids,
        planning_surface_schema_ids=("VSTD-2",),
        verifier_family_ids=(family_id,),
        native_system=native_system,
        native_objects=native_objects,
        native_versions=native_versions,
        native_inputs=native_inputs,
        native_outputs=native_outputs,
        native_result_vocabulary=native_result_vocabulary,
        emitted_schema_ids=emitted_schema_ids,
        supported_relations=supported_relations,
        mechanism_ids=mechanism_ids,
        interaction_modes=interaction_modes,
        domain_tags=domain_tags,
        optional_dependencies=optional_dependencies,
        execution_prerequisites=(
            "EXACT_NATIVE_INPUT",
            "EXACT_IMPLEMENTATION_COORDINATE",
            "RESOURCE_BOUNDS",
            *additional_prerequisites,
        ),
        trust_roots=trust_roots,
        freshness_behavior=freshness_behavior,
        transformation_loss=transformation_loss,
        failure_behavior=failure_behavior,
        availability=ComponentAvailability.AVAILABLE,
        claim_boundary=claim_boundary,
    )


def reference_component_registry() -> InteroperabilityComponentRegistry:
    """Return the immutable first-party planning catalog without running a component."""

    components = (
        _component(
            "component:vstd1-independent-auditor",
            "VSTD-1 satisfiability and grounding auditor",
            ComponentKind.CONSTRAINT,
            "verifier.core.checker:IndependentAuditor.audit_claim_derivation",
            "vstd-1-sat-grounding",
            "Verifier Standard bundled Python auditor",
            ("Boolean formula", "recorded grounding graph"),
            ("VSTD1-CHECKER-REPORT",),
            ("typed-python-arguments-unversioned",),
            ("IndependentAuditReport",),
            ("VERIFIED", "FALSIFIED", "INDETERMINATE"),
            ("mechanism:vstd1-sat-grounding-audit",),
            (InteractionMode.STATIC,),
            domain_tags=("constraint", "grounding", "reference"),
            freshness_behavior="The report reflects only the arguments supplied to one call.",
            transformation_loss="No versioned native input schema exists for the typed call arguments.",
            failure_behavior="Formula disagreement and ungrounded structure remain falsified or indeterminate.",
            claim_boundary="A planned match does not run the auditor or demonstrate actor, implementation, or runtime independence.",
        ),
        _component(
            "component:generic-run-validator",
            "VSTD-1 generic-run receipt validator",
            ComponentKind.VERIFIER,
            "verifier.core.run_validation:validate_run_receipt",
            "generic-run",
            "Verifier Standard generic-run profile",
            ("generic computational run receipt",),
            ("VSTD-1", "generic_computational_run"),
            ("VSTD-1 generic-run JavaScript Object Notation receipt",),
            ("process exit status", "diagnostic output"),
            ("PASS", "FAIL"),
            ("mechanism:generic-run-receipt-validation",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-1",),
            domain_tags=("computation", "receipt", "reference"),
            freshness_behavior="Validation reads the supplied stored receipt and currently reachable artifacts.",
            transformation_loss="Diagnostics are not a new receipt and do not replay the declared command.",
            failure_behavior="Malformed structure, digest mismatch, or missing bound artifacts fail validation.",
            claim_boundary="A planned match does not run validation or establish command correctness, reproduction, or conformance.",
        ),
        _component(
            "component:platform-run-comparator",
            "Bounded operating-system result comparator",
            ComponentKind.COMPARATOR,
            "verifier.core.platform_comparison:compare_platform_run_receipts",
            "platform-comparison",
            "Verifier Standard platform comparison diagnostic",
            ("set of generic-run receipts",),
            ("verifier-platform-comparison-1",),
            ("VSTD-1 generic-run receipt set",),
            ("PlatformComparisonResult",),
            ("PASS", "CONFLICTED", "NOT_ESTABLISHED", "INVALID"),
            ("mechanism:platform-run-comparison",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-1",),
            domain_tags=("cross-platform", "diagnostic", "reference"),
            freshness_behavior="Every comparison is recomputed from the supplied receipt set.",
            transformation_loss="The diagnostic projects only explicitly declared result surfaces.",
            failure_behavior="Missing coverage, incompatibility, disagreement, and invalidity remain distinct.",
            claim_boundary="A planned match does not run comparison or establish universal portability or native-execution attestation.",
        ),
        _component(
            "component:vstd2-geometry-loader",
            "Strict VSTD-2 geometry loader and semantic validator",
            ComponentKind.VERIFIER,
            "verifier.core.geometry_io:load_verification_geometry",
            "vstd-2-geometry",
            "Verifier Standard verification geometry",
            ("VSTD-2 geometry document",),
            ("VSTD-2",),
            ("VSTD-2 JavaScript Object Notation document",),
            ("typed VerificationGeometry",),
            (),
            ("mechanism:vstd2-geometry-validation",),
            (InteractionMode.STATIC,),
            accepted_schema_ids=("VSTD-2",),
            domain_tags=("geometry", "reference", "surface"),
            freshness_behavior="The loader validates the exact supplied mapping or current file bytes.",
            transformation_loss="Integral JSON Schema numbers are normalized to Python integers; source formatting is not retained.",
            failure_behavior="Unknown fields, invalid types, and broken geometry references raise GeometryLoadError.",
            claim_boundary="A planned match does not run loading or establish that the modeled surface is complete in the real world.",
        ),
        _component(
            "component:vstd3-receipt-validator",
            "VSTD-3 hardware receipt validator",
            ComponentKind.VERIFIER,
            "verifier.hardware.validation:validate_vstd3_receipt",
            "vstd-3-hardware",
            "Verifier Standard substrate-accountability model",
            ("VSTD-3 hardware receipt",),
            ("VSTD-3.0",),
            ("typed VSTD3Receipt",),
            ("ReceiptValidation",),
            ("PASS", "FAIL", "UNKNOWN"),
            ("mechanism:vstd3-hardware-receipt-validation",),
            (InteractionMode.OFFLINE_REPLAY,),
            domain_tags=("hardware", "receipt", "reference"),
            freshness_behavior="Freshness is evaluated from receipt timestamps, nonces, and supplied continuity evidence.",
            transformation_loss="Host inventory and normalized vendor fields do not become device attestation.",
            failure_behavior="Missing trust roots or incomplete evidence remain failed or unknown under the profile rules.",
            claim_boundary="A planned match does not run validation or establish production vendor attestation or physical-device identity.",
        ),
        _component(
            "component:vstd4-grounded-certificate-kernel",
            "VSTD-4 grounded decision certificate kernel",
            ComponentKind.CONSTRAINT,
            "verifier.core.kernel:check",
            "vstd-4-evidence-bound",
            "Verifier Standard grounded certificate kernel",
            ("grounded decision certificate",),
            ("VSTD4-GDC-1",),
            ("DecisionCertificate", "optional ClaimBinding"),
            ("KernelResult",),
            ("ACCEPTED", "REJECTED", "REFUSED"),
            ("mechanism:vstd4-grounded-certificate-check",),
            (InteractionMode.STATIC,),
            domain_tags=("certificate", "constraint", "reference"),
            freshness_behavior="The kernel checks one supplied certificate and optional binding.",
            transformation_loss="The certificate proves only its encoded and grounded finite proposition.",
            failure_behavior="Malformed, ungrounded, or invalid derivations are rejected.",
            claim_boundary="A planned match does not run the kernel or establish that the encoded proposition captures the world correctly.",
        ),
        _component(
            "component:vstd4-refutation-producer",
            "Bounded VSTD-4 refutation proof producer",
            ComponentKind.PROVER,
            "verifier.core.refutation:ProofProducingDPLL.solve",
            "vstd-4-evidence-bound",
            "Verifier Standard bounded refutation producer",
            ("Boolean formula",),
            ("VSTD4-RUP-1",),
            ("typed conjunctive-normal-form clauses", "declared proof bounds"),
            ("ProofSearchResult", "optional RefutationCertificate"),
            ("SAT", "UNSAT", "UNKNOWN"),
            ("mechanism:vstd4-refutation-proof-production",),
            (InteractionMode.STATIC,),
            supported_relations=("PRODUCES_CHECKABLE_REFUTATION",),
            domain_tags=("certificate", "proof", "reference"),
            freshness_behavior="The producer searches from the supplied formula under the declared bounds.",
            transformation_loss="A bound-exceeded result carries no proof and remains UNKNOWN.",
            failure_behavior="Proof or decision bounds terminate search as UNKNOWN rather than a verdict.",
            claim_boundary="A planned match does not run proof search or establish that a formula encodes the intended real-world proposition.",
        ),
        _component(
            "component:vstd4-refutation-checker",
            "VSTD-4 reverse-unit-propagation proof checker",
            ComponentKind.CHECKER,
            "verifier.core.refutation:RefutationChecker.check",
            "vstd-4-evidence-bound",
            "Verifier Standard bounded refutation checker",
            ("Boolean formula", "refutation certificate"),
            ("VSTD4-RUP-1",),
            ("typed conjunctive-normal-form clauses", "RefutationCertificate"),
            ("RefutationCheckResult",),
            ("ACCEPTED", "REJECTED"),
            ("mechanism:vstd4-refutation-proof-check",),
            (InteractionMode.STATIC,),
            supported_relations=("PRODUCES_CHECKABLE_REFUTATION",),
            domain_tags=("certificate", "checker", "reference"),
            freshness_behavior="The checker evaluates the supplied formula and proof without re-solving.",
            transformation_loss="Acceptance is limited to reverse-unit-propagation validity of the supplied proof.",
            failure_behavior="A malformed, truncated, or non-implied proof step is rejected.",
            claim_boundary="A planned match does not run proof checking or establish formula grounding, actor independence, or external truth.",
        ),
        _component(
            "component:vstd4-evidence-rechecker",
            "VSTD-4 evidence-bound receipt rechecker",
            ComponentKind.VERIFIER,
            "verifier.core.depth:recheck_evidence_bound_vstd4_receipt",
            "vstd-4-evidence-bound",
            "Verifier Standard evidence-bound VSTD-4 profile",
            ("VSTD-4 evidence-bound receipt",),
            ("VSTD-4", "EVIDENCE_BOUND"),
            ("VSTD-4 receipt", "EvidenceStore", "mechanism registry"),
            ("EvidenceBoundDepthResult",),
            ("ESTABLISHED", "NOT_ESTABLISHED"),
            ("mechanism:vstd4-evidence-bound-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-4",),
            domain_tags=("evidence", "receipt", "reference"),
            freshness_behavior="Recheck rehashes evidence and reruns registered mechanisms at call time.",
            transformation_loss="The result is bounded to registered mechanisms, roots, and declared resource limits.",
            failure_behavior="Missing evidence, mechanism drift, or kernel failure prevents establishment.",
            claim_boundary="A planned match does not run recheck or establish correctness beyond the bound mechanisms and trust roots.",
        ),
        _component(
            "component:vstd5-witness-rechecker",
            "VSTD-5 witness corroboration rechecker",
            ComponentKind.VERIFIER,
            "verifier.core.witness:recheck_vstd5_receipt",
            "vstd-5-witness",
            "Verifier Standard witness corroboration profile",
            ("VSTD-5 witness receipt",),
            ("VSTD-5",),
            ("VSTD-5 receipt", "EvidenceStore", "mechanism registry"),
            ("WitnessCorroborationResult",),
            ("CORROBORATED", "REFUTED", "UNKNOWN", "CONFLICTED"),
            ("mechanism:vstd5-witness-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("VSTD-5",),
            domain_tags=("corroboration", "receipt", "witness"),
            freshness_behavior="Recheck repeats every bound witness mechanism against the supplied evidence store.",
            transformation_loss="Normalized dimensions retain native disagreement but cannot create independent witnesses.",
            failure_behavior="Contradiction and unresolved independence remain conflicted or unknown.",
            claim_boundary="A planned match does not run recheck, create an external witness, or establish independence by agreement.",
        ),
        _component(
            "component:graph-topology-analyzer",
            "Experimental exact-graph-bound topology analyzer",
            ComponentKind.CONSTRAINT,
            "verifier.interoperability.graph_topology:analyze_graph_topology",
            "vstd-graph",
            "Verifier Standard experimental graph topology interpretation",
            ("recorded provenance hypergraph", "exact graph and port-bound topology contract"),
            ("verifier-graph-topology-experimental-1",),
            ("typed ProvenanceHypergraph", "typed GraphTopologyContract", "max_assignments bound"),
            ("GraphTopologyReport",),
            ("CONSISTENT", "CONFLICTED", "NOT_ESTABLISHED", "INVALID"),
            ("mechanism:graph-topology-analysis",),
            (InteractionMode.STATIC,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            emitted_schema_ids=("verifier-graph-topology-report-experimental-1",),
            supported_relations=("relation:graph-topology",),
            domain_tags=("constraint", "experimental", "graph", "topology"),
            freshness_behavior="Analysis binds the exact supplied graph and selected ports, contract, and assignment bound at call time.",
            transformation_loss="Stored contracts are loaded separately; this callable accepts typed objects, not serialized input. Simultaneous classical Boolean equations and temporal offsets per declared clock and unit do not reinterpret provenance as physical causality.",
            failure_behavior="Results remain separate facets with no aggregate verdict. Malformed bindings are invalid; unsupported or incomplete analysis remains NOT_ESTABLISHED. Boolean analysis is bounded to 12 variables, 128 equations, and at most 4096 assignments.",
            claim_boundary="A planned match does not execute the analyzer, establish physical causality, grant mechanism-earned forward artifact support (TRUST), or confer execution authority.",
        ),
        _component(
            "component:composed-untraversability-analyzer",
            "Experimental composed-graph untraversability analyzer",
            ComponentKind.CONSTRAINT,
            "verifier.interoperability.untraversable:analyze_untraversability",
            "vstd-graph",
            "Verifier Standard experimental confidentiality-of-awareness analysis",
            (
                "recorded provenance hypergraph",
                "observer-relative higher-order interface contract",
                "evidence-bound inference rules",
            ),
            ("verifier-untraversable-experimental-1",),
            (
                "typed ProvenanceHypergraph",
                "typed UntraversableContract",
                "VerificationSession",
            ),
            ("UntraversabilityReport",),
            ("MATCH", "FAIL", "UNKNOWN", "CONFLICTED"),
            ("mechanism:composed-untraversability-analysis",),
            (InteractionMode.STATIC, InteractionMode.OFFLINE_REPLAY),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            emitted_schema_ids=(
                "verifier-untraversable-report-experimental-1",
            ),
            supported_relations=("relation:composed-untraversability",),
            domain_tags=(
                "confidentiality-of-awareness",
                "experimental",
                "graph",
                "inference",
            ),
            freshness_behavior="Analysis reruns registered evidence mechanisms and finite closure for the exact graph, observer, interfaces, transcript, interval, capabilities, and resource coordinate.",
            transformation_loss="Facts use caller-selected identifiers and commitments; identifiers and relationship metadata may themselves disclose. Raw protected contents and unmodeled inference or side-channel semantics are outside the report.",
            failure_behavior="A supported hyperpath is FAIL; conflicting relevant rule evidence remains CONFLICTED; missing evidence, incomplete coverage, unsupported semantics, or exhausted bounds remain UNKNOWN. Evidence ceilings cover unique payloads, not repeated mechanism work.",
            claim_boundary="A planned match does not execute the analyzer. MATCH establishes only bounded closure of the declared complete model and grants no universal confidentiality, authorization, identity, intent, conformance, or execution authority.",
        ),
        _component(
            "component:vstd-graph-receipt-validator",
            "VSTD-GRAPH receipt validator",
            ComponentKind.VERIFIER,
            "verifier.data.receipt:validate_data_receipt",
            "vstd-graph",
            "Verifier Standard provenance hypergraph receipt",
            ("VSTD-GRAPH-1 receipt",),
            ("verifier-data-1",),
            ("verifier-data-1 JavaScript Object Notation receipt",),
            ("process exit status", "diagnostic output"),
            ("PASS", "FAIL"),
            ("mechanism:vstd-graph-receipt-validation",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("verifier-data-1",),
            domain_tags=("graph", "provenance", "receipt"),
            freshness_behavior="Validation reads the supplied stored graph receipt and its recorded state.",
            transformation_loss="Recorded reachability does not represent omitted lineage or real-world causality.",
            failure_behavior="Malformed shape, digest mismatch, and invalid recorded graph structure fail validation.",
            claim_boundary="A planned match does not run validation or establish that recorded lineage is complete or causal.",
        ),
        _component(
            "component:vstd-graph-level-rechecker",
            "Evidence-bound VSTD-GRAPH profile rechecker",
            ComponentKind.VERIFIER,
            "verifier.data.graph_level:recheck_evidence_bound_graph_level_record",
            "vstd-graph",
            "Verifier Standard evidence-bound graph profiles",
            ("evidence-bound graph-level record",),
            ("verifier-data-1", "MECHANISM_EVALUATED"),
            ("graph-level record", "EvidenceStore", "mechanism registry"),
            ("EvidenceBoundGraphLevelResult",),
            ("ESTABLISHED", "NOT_ESTABLISHED"),
            ("mechanism:vstd-graph-level-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            domain_tags=("evidence", "graph", "reference"),
            freshness_behavior="Recheck reruns bound object and edge mechanisms over the supplied collection.",
            transformation_loss="The result is limited to the declared, deduplicated graph collection.",
            failure_behavior="Missing evidence or any nonpassing required mechanism prevents establishment.",
            claim_boundary="A planned match does not run recheck or establish hidden members, omitted edges, or complete causality.",
        ),
        _component(
            "component:vstd-graph-assurance-rechecker",
            "VSTD-GRAPH assurance-log rechecker",
            ComponentKind.VERIFIER,
            "verifier.data.assurance:recheck_assurance_log",
            "vstd-graph-assurance",
            "Verifier Standard assurance event log",
            ("VSTD-GRAPH assurance log",),
            ("verifier-graph-assurance-1",),
            ("assurance log", "EvidenceStore", "mechanism registry"),
            ("AssuranceLedger",),
            (),
            ("mechanism:vstd-graph-assurance-log-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("verifier-graph-assurance-1",),
            domain_tags=("assurance", "graph", "replay"),
            freshness_behavior="Replay rehashes the historical graph and reruns evidence-bound event mechanisms.",
            transformation_loss="Graph propagation remains bounded diagnostic support and not universal assurance.",
            failure_behavior="The callable returns a replayed AssuranceLedger or raises AssuranceFlowError on hash-chain, evidence, or mechanism mismatch; it emits no aggregate status vocabulary.",
            claim_boundary="A planned match does not run replay or convert graph proximity into correctness, responsibility, or guilt.",
        ),
        _component(
            "component:artifact-bundle-verifier",
            "Artifact freeze and seal verifier",
            ComponentKind.VERIFIER,
            "verifier.artifact_control:verify_frozen_artifact",
            "artifact-control",
            "Verifier Standard artifact control",
            ("frozen artifact bundle",),
            ("verifier-artifact-freeze-1", "verifier-artifact-seal-1"),
            ("artifact-control bundle path", "optional expected anchors"),
            ("ArtifactVerification",),
            ("FAIL", "CONFLICTED", "SEALED", "FROZEN_UNSEALED", "NOT_ESTABLISHED"),
            ("mechanism:artifact-bundle-verification",),
            (InteractionMode.OFFLINE_REPLAY,),
            accepted_schema_ids=("verifier-artifact-freeze-1", "verifier-artifact-seal-1"),
            optional_dependencies=("cryptography for seal verification",),
            domain_tags=("artifact", "integrity", "reference"),
            freshness_behavior="Verification re-reads current bundle paths and bytes on every call.",
            transformation_loss="Byte identity does not establish semantic correctness, custody, or trusted time.",
            failure_behavior="Byte, guard, seal, or expected-anchor mismatch cannot produce a clean state.",
            claim_boundary="A planned match does not run artifact verification or establish semantic correctness, custody, or encryption.",
        ),
        _component(
            "component:artifact-network-authority-composition-assessor",
            "Experimental finite authority-composition assessor",
            ComponentKind.CHECKER,
            "verifier.interoperability.authority_composition:assess_authority_composition",
            "artifact-network",
            "Verifier Standard experimental finite authority composition",
            ("exact finite authority-composition declaration", "digest-keyed commit and authority-model bytes"),
            ("verifier-finite-authority-composition-profile-1", "ASYNCHRONOUS_INTERLEAVING", _AUTHORITY_COMPOSITION_PROFILE_DIGEST),
            ("verifier-finite-authority-composition-1 canonical bytes", "digest-keyed immutable evidence mapping"),
            ("verifier-finite-authority-composition-result-1 decoded object",),
            ("BOUND", "MATCHED", "MISMATCH", "PRESERVED", "VIOLATED", "INVALID", "UNKNOWN"),
            ("mechanism:finite-authority-composition-assessment",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("verifier-finite-authority-composition-1",),
            emitted_schema_ids=("verifier-finite-authority-composition-result-1",),
            supported_relations=("relation:assesses-finite-authority-composition",),
            domain_tags=("artifact", "authority", "composition", "experimental"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_AUTHORITY_COMPOSITION_PROFILE_DIGEST}",),
            freshness_behavior="Each call binds exact member and composite commits and model selections, then enumerates the bounded reachable asynchronous-interleaving product from supplied bytes without storage reads.",
            transformation_loss="The compiled inert profile identifies the declared rule, not implementation or execution identity. The retained FINITE_AUTHORITY_COMPOSITION.md specification bounds the model translation; the evidence mapping has no standalone serialized schema.",
            failure_behavior="Malformed binding remains INVALID; missing evidence, unsupported profiles and exceeded bounds remain UNKNOWN; definite correspondence mismatches and reachable authority removals remain separate negative results.",
            claim_boundary="A planned match neither runs assessment nor establishes native input validity. Finite correspondence does not establish source grounding, self-derivation, stronger completeness, runtime behavior, general agency, or a six-axis silo-status upgrade.",
        ),
        _component(
            "component:artifact-network-finite-composition-qualifier",
            "Experimental selected finite silo-composition qualifier",
            ComponentKind.CHECKER,
            "verifier.interoperability.composition_qualification:qualify_silo_composition",
            "artifact-network",
            "Verifier Standard experimental verification-artifact network and finite authority composition",
            ("exact selected local silo composition", "separate legacy and finite composition assessments"),
            ("verifier-silo-composition-mechanism-1", "verifier-finite-authority-composition-profile-1", "ASYNCHRONOUS_INTERLEAVING", _AUTHORITY_COMPOSITION_PROFILE_DIGEST),
            (
                "local path to verifier-finite-authority-composition-1 canonical bytes",
                "ordered local (ContentAddressedStore root, silo-commit path) member pairs",
                "local composite ContentAddressedStore root",
                "local composite silo-commit path",
            ),
            ("unversioned composition qualification report retaining legacy and finite assessments",),
            ("FINITE_COMPOSITION_QUALIFIED", "NOT_QUALIFIED"),
            ("mechanism:artifact-network-finite-composition-qualification",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("verifier-finite-authority-composition-1", "verifier-silo-commit-1"),
            supported_relations=("relation:qualifies-selected-finite-silo-composition",),
            domain_tags=("artifact", "authority", "composition", "experimental", "network"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_AUTHORITY_COMPOSITION_PROFILE_DIGEST}", "EXACT_SELECTED_LOCAL_SILO_INPUTS"),
            freshness_behavior="Each call reads the bounded local declaration and selected commit paths plus current content-addressed-store objects, then separately recomputes legacy admission and the finite asynchronous-interleaving assessment. Commit files are captured once per normalized path, but the full filesystem observation is not atomic.",
            transformation_loss="The local path and sequence arguments have no standalone serialized call schema, and the qualification report has no standalone wire discriminator. Nested finite results retain their own schema; selected byte digests do not establish source, custody, runtime, or implementation identity.",
            failure_behavior="Qualification requires exact selection binding, legacy ADMISSIBLE, finite BOUND coordinates, MATCHED transitions, and both PRESERVED results. Malformed input remains INVALID; missing, unsupported, or bounded observations remain UNKNOWN or NOT_QUALIFIED, with both nested assessments and residual obligations retained.",
            claim_boundary="A planned match or READY preflight does not run qualification, validate native local inputs, grant authorization, or close a geometry hole. Qualification is not a portable replay receipt, atomic filesystem snapshot, source proof, runtime/model correspondence, general composed agency result, or six-axis silo-status upgrade.",
        ),
        _component(
            "component:artifact-network-composition-declaration-decoder",
            "Experimental strict silo-composition declaration decoder",
            ComponentKind.ADAPTER,
            "verifier.interoperability.network:SiloComposition.from_dict",
            "artifact-network",
            "Verifier Standard experimental verification-artifact network",
            ("exact silo-composition declaration",),
            ("verifier-silo-composition-1",),
            ("verifier-silo-composition-1 decoded object",),
            ("SiloComposition",),
            (),
            ("mechanism:artifact-network-composition-declaration-decode",),
            (InteractionMode.STATIC,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("verifier-silo-composition-1",),
            supported_relations=("relation:decodes-silo-composition-declaration",),
            domain_tags=("artifact", "composition", "experimental", "network"),
            freshness_behavior="Each call strictly reconstructs the supplied declaration and rejects noncanonical member order, duplicate members, unknown fields, and malformed digests.",
            transformation_loss="Decoding retains exact member and optional composite commit digests but resolves no commit bytes or graph edges.",
            failure_behavior="Malformed or noncanonical declarations raise NetworkError rather than yielding a partial declaration.",
            claim_boundary="A planned match does not run declaration decoding, resolve members, check general graph edges, establish TypeScript support, or grant composition admissibility.",
        ),
        _component(
            "component:artifact-network-composition-receipt-builder",
            "Experimental silo-composition assessment receipt builder",
            ComponentKind.COLLECTOR,
            "verifier.interoperability.network:build_silo_composition_assessment_receipt",
            "artifact-network",
            "Verifier Standard experimental verification-artifact network",
            ("typed silo-composition declaration", "resolved member silos", "optional resolved composite silo"),
            ("verifier-silo-composition-mechanism-1",),
            ("SiloComposition", "ordered SiloCommit and ContentAddressedStore pairs"),
            ("SiloCompositionAssessmentReceipt",),
            ("ADMISSIBLE", "NOT_ADMISSIBLE"),
            ("mechanism:artifact-network-composition-receipt-construction",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            emitted_schema_ids=("verifier-silo-composition-assessment-receipt-1",),
            supported_relations=("relation:constructs-silo-composition-assessment-receipt",),
            domain_tags=("artifact", "composition", "experimental", "receipt"),
            freshness_behavior="Each call recomputes member and optional composite silo assessments from the supplied current content-addressed stores before binding the declaration, mechanism, nested receipts, and result.",
            transformation_loss="The receipt covers only the exact declared silo composition and reference mechanism; it is not a general graph-edge assessment.",
            failure_behavior="Unresolved, substituted, duplicate, or declaration-mismatched members raise NetworkError; nonadmissible assessed states remain NOT_ADMISSIBLE.",
            claim_boundary="A planned match does not run receipt construction, establish an independently implemented checker, check general graph edges, establish TypeScript support, or prove artifact truth.",
        ),
        _component(
            "component:artifact-network-composition-receipt-rechecker",
            "Experimental silo-composition assessment receipt rechecker",
            ComponentKind.VERIFIER,
            "verifier.interoperability.network:recheck_silo_composition_assessment_receipt",
            "artifact-network",
            "Verifier Standard experimental verification-artifact network",
            ("silo-composition assessment receipt", "exact declaration and resolved silos"),
            ("verifier-silo-composition-assessment-receipt-1",),
            ("SiloComposition", "SiloCompositionAssessmentReceipt or decoded receipt object", "ordered SiloCommit and ContentAddressedStore pairs"),
            ("None on exact independent recomputation",),
            (),
            ("mechanism:artifact-network-composition-receipt-independent-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("verifier-silo-composition-assessment-receipt-1",),
            supported_relations=("relation:rechecks-silo-composition-assessment-receipt",),
            domain_tags=("artifact", "composition", "experimental", "receipt"),
            freshness_behavior="Each call independently recomputes the complete reference receipt from the supplied declaration, current stores, and exact member and optional composite commits, then compares canonical bytes.",
            transformation_loss="Equality establishes agreement with the same reference mechanism at the supplied coordinate, not implementation independence or a general graph-edge result.",
            failure_behavior="Malformed receipts, changed evidence, declaration drift, mechanism drift, or any canonical mismatch raise NetworkError.",
            claim_boundary="A planned match does not run receipt rechecking, supply an independent implementation, check general graph edges, establish TypeScript support, or extend the receipt beyond its declared silos.",
        ),
        _component(
            "component:artifact-network-proposition-transfer-assessor",
            "Experimental finite-set proposition-transfer assessor",
            ComponentKind.CHECKER,
            "verifier.interoperability.proposition_transfer:assess_transfer",
            "artifact-network",
            "Verifier Standard experimental direct finite-set transfer",
            ("exact proposition-transfer declaration", "digest-keyed commit and artifact bytes"),
            ("verifier-proposition-transfer-rule-1", "canonical_finite_set_union_v1", _TRANSFER_PROFILE_DIGEST),
            ("verifier-proposition-transfer-1 canonical bytes", "digest-keyed immutable evidence mapping"),
            ("verifier-proposition-transfer-assessment-1 decoded object",),
            ("PASS", "FAIL", "INVALID", "UNKNOWN", "SUPPORTED", "NOT_ESTABLISHED"),
            ("mechanism:artifact-network-proposition-transfer-assessment",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("verifier-proposition-transfer-1",),
            emitted_schema_ids=("verifier-proposition-transfer-assessment-1",),
            supported_relations=("relation:assesses-proposition-transfer",),
            domain_tags=("artifact", "experimental", "finite-set", "proposition-transfer"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_TRANSFER_PROFILE_DIGEST}",),
            freshness_behavior="Every call rechecks exact commit, census, artifact and context coordinates from retained bounded input bytes; it performs no storage reads.",
            transformation_loss=f"The compiled semantic profile is mirrored at {_TRANSFER_PROFILE_PATH}; profile identity is not implementation or execution identity. Native evidence mappings have no standalone serialized schema.",
            failure_behavior="Malformed declarations raise PropositionTransferError; unsupported rules remain UNKNOWN, missing evidence does not erase known negatives, and a true target does not repair a failed transfer.",
            claim_boundary="A planned mechanism match does not establish rule-profile compatibility or run assessment. Native results do not establish execution identity, authority, graph-wide deduction, six-axis silo completeness, or universal truth.",
        ),
        _component(
            "component:artifact-network-proposition-transfer-rechecker",
            "Experimental finite-set proposition-transfer receipt rechecker",
            ComponentKind.CHECKER,
            "verifier.interoperability.proposition_transfer:recheck_transfer_receipt",
            "artifact-network",
            "Verifier Standard experimental direct finite-set transfer",
            ("exact proposition-transfer declaration and receipt", "digest-keyed commit and artifact bytes"),
            ("verifier-proposition-transfer-rule-1", "canonical_finite_set_union_v1", _TRANSFER_PROFILE_DIGEST),
            ("verifier-proposition-transfer-1 canonical bytes", "verifier-proposition-transfer-receipt-1 canonical bytes", "digest-keyed immutable evidence mapping"),
            ("verifier-proposition-transfer-assessment-1 decoded object",),
            ("PASS", "FAIL", "INVALID", "UNKNOWN", "SUPPORTED", "NOT_ESTABLISHED"),
            ("mechanism:artifact-network-proposition-transfer-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("verifier-proposition-transfer-1", "verifier-proposition-transfer-receipt-1"),
            emitted_schema_ids=("verifier-proposition-transfer-assessment-1",),
            supported_relations=("relation:rechecks-proposition-transfer-receipt",),
            domain_tags=("artifact", "experimental", "finite-set", "proposition-transfer", "receipt"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_TRANSFER_PROFILE_DIGEST}",),
            freshness_behavior="Every call rebuilds the complete semantic receipt using current supplied bounded evidence and compares exact canonical bytes, including negative and unknown fields.",
            transformation_loss=f"The compiled semantic profile is mirrored at {_TRANSFER_PROFILE_PATH}; replay equality is not independent implementation or execution identity. Native evidence mappings have no standalone serialized schema.",
            failure_behavior="Malformed records or wrong declaration/profile binding raise PropositionTransferError; unequal current replay raises TRANSFER_NOT_REPRODUCED, not a forgery or negation verdict. Reproduced FAIL and UNKNOWN results remain negative or unknown.",
            claim_boundary="A planned mechanism match does not establish rule-profile compatibility or run rechecking. Receipt equality does not establish execution identity, authority, graph-wide deduction, six-axis silo completeness, or universal truth.",
        ),
        _component(
            "component:artifact-network-typed-formation-producer",
            "Experimental finite typed-formation certificate producer",
            ComponentKind.PROVER,
            "verifier.interoperability.formation_producer:produce_formation_certificate",
            "artifact-network",
            "Verifier Standard experimental finite typed formation",
            ("finite typed-formation subject",),
            ("verifier-typed-formation-profile-1", _FORMATION_PROFILE_DIGEST),
            ("verifier-typed-formation-1 canonical immutable subject bytes",),
            ("verifier-typed-formation-certificate-1 canonical immutable certificate bytes",),
            (),
            ("mechanism:typed-formation-certificate-production",),
            (InteractionMode.STATIC,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("verifier-typed-formation-1",),
            emitted_schema_ids=("verifier-typed-formation-certificate-1",),
            supported_relations=("relation:produces-typed-formation-certificate",),
            domain_tags=("artifact", "certificate", "experimental", "typed-formation"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_FORMATION_PROFILE_DIGEST}",),
            freshness_behavior="Each call constructs a certificate for exactly one supplied finite subject and the compiled profile; it does not call the checker.",
            transformation_loss=f"The inert profile is retained at {_FORMATION_PROFILE_PATH}; src/verifier/specifications/TYPED_FORMATION.md and src/verifier/schemas/verifier-typed-formation-1.schema.json define the bounded contract. Certificate production emits no acceptance verdict and does not discharge residual source obligations.",
            failure_behavior="Malformed syntax or incompatible formation raises FormationError; unsupported schema/profile raises UnsupportedFormation and exceeded finite bounds raise FormationLimitError. No partial certificate is returned.",
            claim_boundary=_FORMATION_BOUNDARY,
        ),
        _component(
            "component:artifact-network-typed-formation-checker",
            "Experimental finite typed-formation certificate checker",
            ComponentKind.CHECKER,
            "verifier.interoperability.formation_checker:check_formation",
            "artifact-network",
            "Verifier Standard experimental finite typed formation",
            ("finite typed-formation subject", "exact formation certificate"),
            ("verifier-typed-formation-profile-1", _FORMATION_PROFILE_DIGEST),
            ("verifier-typed-formation-1 canonical immutable subject bytes", "verifier-typed-formation-certificate-1 canonical immutable certificate bytes"),
            ("typed-formation report mapping (unversioned)",),
            ("CHECKED", "INVALID", "UNKNOWN"),
            ("mechanism:typed-formation-certificate-check",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("verifier-typed-formation-1", "verifier-typed-formation-certificate-1"),
            supported_relations=("relation:checks-typed-formation-certificate",),
            domain_tags=("artifact", "certificate", "experimental", "typed-formation"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_FORMATION_PROFILE_DIGEST}",),
            freshness_behavior="Every call independently reconstructs finite typed nodes and paths from the exact supplied subject and certificate bytes; no producer, stored verdict or external artifact is consulted.",
            transformation_loss=f"The inert profile is retained at {_FORMATION_PROFILE_PATH}; profile identity is not implementation identity. The report has no standalone serialized schema, preserves all residual obligations, and distinguishes normalized denotation from exact formation identity.",
            failure_behavior="Known malformed or substituted records, proof steps, types and endpoints yield INVALID; unsupported schema/profile and exceeded resource ceilings yield UNKNOWN. Only a complete bounded check yields CHECKED.",
            claim_boundary=_FORMATION_BOUNDARY,
        ),
        _component(
            "component:artifact-network-typed-formation-receipt-rechecker",
            "Experimental finite-formation receipt rechecker",
            ComponentKind.CHECKER,
            "verifier.interoperability.formation_receipt:recheck_formation_receipt",
            "artifact-network",
            "Verifier Standard experimental finite typed formation",
            ("exact formation selection and receipt", "selected commit and observed census bytes"),
            ("verifier-typed-formation-profile-1", _FORMATION_PROFILE_DIGEST),
            ("verifier-silo-formation-selection-1 canonical immutable selection bytes", "verifier-silo-commit-1 canonical immutable commit bytes", "verifier-silo-formation-receipt-1 canonical immutable receipt bytes", "bounded ordinary digest-keyed immutable evidence dictionary"),
            ("retained-silo formation inspection mapping (unversioned)",),
            ("BOUND", "COMPLETE", "INCOMPLETE", "MATCHED", "CHECKED", "INVALID", "UNKNOWN"),
            ("mechanism:typed-formation-receipt-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("verifier-silo-commit-1", "verifier-silo-formation-receipt-1", "verifier-silo-formation-selection-1"),
            supported_relations=("relation:rechecks-typed-formation-receipt",),
            domain_tags=("artifact", "experimental", "receipt", "typed-formation"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_FORMATION_PROFILE_DIGEST}", "EXACT_FORMATION_SELECTION", "OBSERVED_CENSUS_BYTES"),
            freshness_behavior="Every call captures bounded input bytes, reruns formation inspection, reconstructs the observed-evidence-bound receipt and compares its complete canonical bytes. No stored verdict is trusted or submitted code executed.",
            transformation_loss=f"The inert profile is retained at {_FORMATION_PROFILE_PATH}; src/verifier/specifications/FORMATION_RECEIPT.md defines strict selection and observed-evidence binding. The returned inspection has no standalone wire discriminator. Receipt identity is not implementation or execution identity; provider diagnostics are not portable evidence bytes.",
            failure_behavior="Malformed, unsupported, over-budget or mismatched input raises FormationReceiptError. Unequal replay is FORMATION_RECEIPT_NOT_REPRODUCED, not forgery or claim negation. Reproduced INVALID, UNKNOWN and INCOMPLETE remain negative or uncertain results.",
            claim_boundary=_FORMATION_BOUNDARY,
        ),
        _component(
            "component:artifact-network-typed-formation-session-mechanism",
            "Experimental typed-formation native session adapter",
            ComponentKind.ADAPTER,
            "verifier.interoperability.formation_mechanism:FormationPathCertificateMechanism.evaluate",
            "artifact-network",
            "Verifier Standard experimental finite typed formation",
            ("exact evidence-bound formation proposition", "ordered subject and certificate bytes"),
            ("verifier-typed-formation-profile-1", "vstd.typed_formation.checked.0.1", _FORMATION_PROFILE_DIGEST),
            ("BoundProposition typed native declaration (unversioned)", "ordered immutable subject/certificate byte pair (unversioned)"),
            ("MechanismDecision with preserved formation_report and residual_obligations (unversioned)",),
            ("PASS", "FAIL", "UNKNOWN"),
            ("vstd.typed_formation.checked.0.1",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            supported_relations=("relation:checks-bound-typed-formation-proposition",),
            domain_tags=("artifact", "certificate", "experimental", "typed-formation"),
            additional_prerequisites=(f"EXACT_RULE_PROFILE:{_FORMATION_PROFILE_DIGEST}", "EXACT_BOUND_PROPOSITION", "DECLARED_CONTEXT_DIGESTS", "EXPLICIT_MECHANISM_INSTANCE"),
            freshness_behavior="This reference names an unbound instance method: explicitly construct FormationPathCertificateMechanism() and invoke its bound evaluate, or register that instance in VerificationSession. Catalog matching never instantiates it. Admitted evaluation requires exact predicate, expected CHECKED, profile, subject and declared context bindings, and rehashes the ordered evidence pair. Early refusals can precede pure checking.",
            transformation_loss=f"The inert profile is retained at {_FORMATION_PROFILE_PATH}; this typed wrapper has no standalone serialized input or result schema. Its implementation digest binds four selected source files plus profile, not loaded code or full dependencies. Ground and agency trust roots remain declared assumptions.",
            failure_behavior="Recognized binding or formation failures yield FAIL only for the exact certificate predicate; unsupported declarations, missing evidence, exhausted bounds and execution failure remain UNKNOWN. Pure checker results and every residual obligation remain separate.",
            claim_boundary=_FORMATION_BOUNDARY,
        ),
        _component(
            "component:artifact-network-transfer-materializer",
            "Experimental artifact-network transfer materializer",
            ComponentKind.ADAPTER,
            "verifier.interoperability.network:materialize_silo_transfer",
            "artifact-network",
            "Verifier Standard experimental verification-artifact network",
            ("bounded signed complete-snapshot silo transfer",),
            ("verifier-silo-transfer-1",),
            ("canonical transfer bytes or decoded transfer object", "absent destination path"),
            ("verifier-silo-export-1 portable manifest", "materialized content-addressed silo"),
            (),
            ("mechanism:artifact-network-transfer-materialization",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("verifier-silo-transfer-1",),
            emitted_schema_ids=("verifier-silo-export-1",),
            optional_dependencies=("cryptography for Ed25519 signature verification",),
            domain_tags=("artifact", "experimental", "interoperability", "network"),
            freshness_behavior="Each call revalidates the supplied transfer bytes and the newly materialized destination tree.",
            transformation_loss="Materialization preserves the selected snapshot bytes but does not preserve a live endpoint, publisher custody, or service history.",
            failure_behavior="Malformed, oversized, incomplete, substituted, noncanonical, or signature-invalid transfers are rejected and cannot leave a successful destination.",
            claim_boundary="A planned match does not run transfer validation, contact a deployed service, establish publisher identity, prove artifact truth, or qualify any untested platform coordinate.",
        ),
        _component(
            "component:artifact-network-source-grounding-assessor",
            "Experimental source-grounding assessor",
            ComponentKind.CHECKER,
            "verifier.interoperability.source_grounding:qualify_source_grounding",
            "vstd-source-grounding",
            "Verifier Standard experimental source-grounding replay",
            ("exact source-grounding declaration", "digest-keyed source and certificate bytes"),
            (
                "verifier-source-grounding-mechanism-profile-1",
                _SOURCE_GROUNDING_PROFILE_DIGEST,
            ),
            (
                "verifier-source-grounding-1 canonical immutable declaration bytes",
                "digest-keyed immutable source and certificate evidence mapping",
            ),
            ("SourceGroundingReceipt",),
            ("ESTABLISHED", "REFUTED", "UNKNOWN", "INVALID"),
            ("mechanism:source-grounding-assessment",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=(
                "verifier-source-grounding-1",
                "verifier-source-grounding-certificate-1",
            ),
            emitted_schema_ids=("verifier-source-grounding-receipt-1",),
            supported_relations=("relation:assesses-source-grounding",),
            domain_tags=("artifact", "experimental", "grounding", "source"),
            additional_prerequisites=(
                f"EXACT_RULE_PROFILE:{_SOURCE_GROUNDING_PROFILE_DIGEST}",
            ),
            freshness_behavior="Each call replays the exact declared proposition from supplied retained source and certificate bytes; it performs no storage or network reads.",
            transformation_loss="The result covers one canonical JavaScript Object Notation path-equality proposition and one semantic frame. Profile identity is not producer or implementation independence.",
            failure_behavior="Substitution, malformed canonical records, circular evidence, and nonreproducing certificates remain INVALID; absent or unsupported evidence remains UNKNOWN.",
            claim_boundary="A planned match does not run source-grounding assessment. An ESTABLISHED bounded proposition does not establish source truth, custody, authorization, broader semantic grounding, or producer independence.",
        ),
        _component(
            "component:artifact-network-source-grounding-receipt-rechecker",
            "Experimental source-grounding receipt rechecker",
            ComponentKind.CHECKER,
            "verifier.interoperability.source_grounding:recheck_source_grounding_receipt",
            "vstd-source-grounding",
            "Verifier Standard experimental source-grounding replay",
            ("source-grounding receipt", "exact declaration and retained evidence bytes"),
            (
                "verifier-source-grounding-mechanism-profile-1",
                _SOURCE_GROUNDING_PROFILE_DIGEST,
            ),
            (
                "verifier-source-grounding-1 canonical immutable declaration bytes",
                "verifier-source-grounding-receipt-1 canonical immutable receipt bytes",
                "digest-keyed immutable source and certificate evidence mapping",
            ),
            ("SourceGroundingReceipt",),
            ("ESTABLISHED", "REFUTED", "UNKNOWN", "INVALID"),
            ("mechanism:source-grounding-receipt-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=(
                "verifier-source-grounding-1",
                "verifier-source-grounding-certificate-1",
                "verifier-source-grounding-receipt-1",
            ),
            supported_relations=("relation:rechecks-source-grounding-receipt",),
            domain_tags=("artifact", "experimental", "grounding", "receipt", "source"),
            additional_prerequisites=(
                f"EXACT_RULE_PROFILE:{_SOURCE_GROUNDING_PROFILE_DIGEST}",
            ),
            freshness_behavior="Each call rebuilds the full receipt from the current supplied declaration and retained evidence, then compares exact canonical bytes.",
            transformation_loss="Exact replay equality uses the same reference mechanism and does not establish an independently implemented checker or historical producer execution.",
            failure_behavior="Malformed records and any current replay mismatch raise SourceGroundingError; reproduced REFUTED and UNKNOWN results remain negative or unknown.",
            claim_boundary="A planned match does not run receipt rechecking. Receipt reproduction does not establish source truth, custody, authorization, broader semantic grounding, or implementation independence.",
        ),
        _component(
            "component:artifact-network-relation-boundary-assessor",
            "Experimental relation-boundary assessor",
            ComponentKind.CHECKER,
            "verifier.interoperability.relation_boundary:qualify_relation_boundary",
            "vstd-relation-boundary",
            "Verifier Standard experimental relation-boundary replay",
            ("exact relation-boundary declaration", "digest-keyed endpoint and execution-evidence bytes"),
            (
                "verifier-relation-boundary-mechanism-profile-1",
                _RELATION_BOUNDARY_PROFILE_DIGEST,
            ),
            (
                "verifier-relation-boundary-1 canonical immutable declaration bytes",
                "digest-keyed immutable source, target, and execution-evidence mapping",
            ),
            ("RelationBoundaryReceipt",),
            ("ESTABLISHED", "REFUTED", "UNKNOWN", "INVALID"),
            ("mechanism:relation-boundary-assessment",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=(
                "verifier-relation-boundary-1",
                "verifier-relation-boundary-evidence-1",
            ),
            emitted_schema_ids=("verifier-relation-boundary-receipt-1",),
            supported_relations=("relation:assesses-relation-boundary",),
            domain_tags=("artifact", "boundary", "experimental", "relation"),
            additional_prerequisites=(
                f"EXACT_RULE_PROFILE:{_RELATION_BOUNDARY_PROFILE_DIGEST}",
            ),
            freshness_behavior="Each call replays the exact declared facet map from supplied source, target, and execution-evidence bytes without storage or network reads.",
            transformation_loss="Only declared consumed, preserved, and lost facets are compared. The bounded map does not infer undeclared semantic equivalence or causal direction.",
            failure_behavior="Aliased evidence, invalid topology, malformed frames, and nonreproducing execution evidence remain INVALID; unsupported frames or missing evidence remain UNKNOWN.",
            claim_boundary="A planned match does not run relation-boundary assessment. ESTABLISHED facet preservation does not establish whole-artifact equivalence, physical causality, source truth, or producer independence.",
        ),
        _component(
            "component:artifact-network-relation-boundary-receipt-rechecker",
            "Experimental relation-boundary receipt rechecker",
            ComponentKind.CHECKER,
            "verifier.interoperability.relation_boundary:recheck_relation_boundary_receipt",
            "vstd-relation-boundary",
            "Verifier Standard experimental relation-boundary replay",
            ("relation-boundary receipt", "exact declaration and retained endpoint evidence"),
            (
                "verifier-relation-boundary-mechanism-profile-1",
                _RELATION_BOUNDARY_PROFILE_DIGEST,
            ),
            (
                "verifier-relation-boundary-1 canonical immutable declaration bytes",
                "verifier-relation-boundary-receipt-1 canonical immutable receipt bytes",
                "digest-keyed immutable source, target, and execution-evidence mapping",
            ),
            ("RelationBoundaryReceipt",),
            ("ESTABLISHED", "REFUTED", "UNKNOWN", "INVALID"),
            ("mechanism:relation-boundary-receipt-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=(
                "verifier-relation-boundary-1",
                "verifier-relation-boundary-evidence-1",
                "verifier-relation-boundary-receipt-1",
            ),
            supported_relations=("relation:rechecks-relation-boundary-receipt",),
            domain_tags=("artifact", "boundary", "experimental", "receipt", "relation"),
            additional_prerequisites=(
                f"EXACT_RULE_PROFILE:{_RELATION_BOUNDARY_PROFILE_DIGEST}",
            ),
            freshness_behavior="Each call rebuilds the relation-boundary receipt from current supplied retained bytes and requires exact canonical reproduction.",
            transformation_loss="Replay equality is scoped to the same declared facet map and reference implementation; it adds no undeclared relation semantics.",
            failure_behavior="Malformed declarations or receipts and any replay mismatch raise RelationBoundaryError; reproduced REFUTED and UNKNOWN remain negative or unknown.",
            claim_boundary="A planned match does not run receipt rechecking. Receipt reproduction does not establish whole-artifact equivalence, physical causality, source truth, or implementation independence.",
        ),
        _component(
            "component:artifact-network-deriver-session-recorder",
            "Experimental bounded deriver session recorder",
            ComponentKind.COLLECTOR,
            "verifier.interoperability.deriver_self_status:record_deriver_session",
            "vstd-deriver-self-status",
            "Verifier Standard experimental bounded native-process runner",
            ("exact deriver-session declaration", "local executable bytes and invocation"),
            (
                "verifier-deriver-self-status-checker-1",
                _DERIVER_SELF_STATUS_PROFILE_DIGEST,
            ),
            (
                "verifier-deriver-self-status-1 canonical immutable declaration bytes",
                "local executable filesystem path",
            ),
            ("DeriverSessionReceipt",),
            (
                "COMPLETED",
                "NOT_RUN",
                "TIMED_OUT",
                "OUTPUT_LIMIT_EXCEEDED",
                "START_FAILED",
                "CAPTURE_FAILED",
            ),
            ("mechanism:bounded-deriver-session-recording",),
            (InteractionMode.LIVE_MUTATING,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=("verifier-deriver-self-status-1",),
            emitted_schema_ids=("verifier-deriver-self-status-receipt-1",),
            supported_relations=("relation:records-deriver-session",),
            domain_tags=("deriver", "execution", "experimental", "receipt"),
            additional_prerequisites=(
                "EXPLICIT_PROCESS_EXECUTION_AUTHORIZATION",
                "PUBLIC_NON_SECRET_ENVIRONMENT",
                "SUPPORTED_WINDOWS_NATIVE_RUNTIME",
            ),
            freshness_behavior="Each call rehashes the selected executable and launches one bounded invocation in a newly created empty working directory.",
            transformation_loss="The receipt retains one exact transcript and runtime coordinate, but not a sandbox, confidential environment, source semantics, or all executable behavior.",
            failure_behavior="Unsupported declarations do not run; start, timeout, output-limit, and capture failures remain explicit invocation states rather than successful transcripts.",
            claim_boundary="A planned match does not authorize or run the deriver. A recorded invocation does not establish self-status, deterministic reproduction, sandboxing, source correctness, completeness, safety, or another runtime.",
        ),
        _component(
            "component:artifact-network-deriver-self-status-rechecker",
            "Experimental actual deriver self-status rechecker",
            ComponentKind.CHECKER,
            "verifier.interoperability.deriver_self_status:recheck_deriver_self_status",
            "vstd-deriver-self-status",
            "Verifier Standard experimental bounded native-process runner",
            ("exact deriver declaration and session receipt", "local executable bytes"),
            (
                "verifier-deriver-self-status-checker-1",
                _DERIVER_SELF_STATUS_PROFILE_DIGEST,
            ),
            (
                "verifier-deriver-self-status-1 canonical immutable declaration bytes",
                "verifier-deriver-self-status-receipt-1 canonical immutable receipt bytes",
                "local executable filesystem path",
            ),
            ("DeriverSelfStatusAssessment",),
            ("ESTABLISHED", "REFUTED", "UNKNOWN", "INVALID"),
            ("mechanism:deriver-self-status-recheck",),
            (InteractionMode.LIVE_MUTATING,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=(
                "verifier-deriver-self-status-1",
                "verifier-deriver-self-status-receipt-1",
            ),
            supported_relations=("relation:rechecks-deriver-session-receipt",),
            domain_tags=("deriver", "execution", "experimental", "receipt"),
            additional_prerequisites=(
                "EXPLICIT_PROCESS_EXECUTION_AUTHORIZATION",
                "PUBLIC_NON_SECRET_ENVIRONMENT",
                "SUPPORTED_WINDOWS_NATIVE_RUNTIME",
            ),
            freshness_behavior="Each supported call rehashes the executable and reruns the exact invocation in a new empty directory before comparing transcript bytes.",
            transformation_loss="ESTABLISHED covers one exact executable and declared runtime coordinate; it is not structural self-derivability, source semantics, or an execution sandbox.",
            failure_behavior="Malformed or inconsistent bindings remain INVALID, reproducible disagreement remains REFUTED, and unsupported or unavailable execution remains UNKNOWN.",
            claim_boundary="A planned match does not authorize or run rechecking. ESTABLISHED self-status does not establish global behavior, source correctness, completeness, safety, authorization, sandboxing, or another runtime.",
        ),
        _component(
            "component:artifact-network-global-cycle-assessor",
            "Experimental grounded global-cycle assessor",
            ComponentKind.CHECKER,
            "verifier.interoperability.global_cycle_assessment:assess_global_cycles",
            "vstd-global-cycle",
            "Verifier Standard experimental grounded finite-graph cycle replay",
            ("exact global-cycle declaration", "grounded relation-boundary materials"),
            (
                "verifier-global-cycle-assessment-1",
                "verifier-cycle-relation-semantics-1",
                _SOURCE_GROUNDING_PROFILE_DIGEST,
                _RELATION_BOUNDARY_PROFILE_DIGEST,
            ),
            (
                "verifier-global-cycle-assessment-1 canonical immutable declaration bytes",
                "digest-keyed typed CycleRelationMaterial mapping",
                "bounded maximum-work integer",
            ),
            ("GlobalCycleReceipt",),
            ("ASSESSED", "CONFLICTED", "UNKNOWN", "INVALID"),
            ("mechanism:grounded-global-cycle-assessment",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=(
                "verifier-cycle-relation-semantics-1",
                "verifier-global-cycle-assessment-1",
                "verifier-relation-boundary-receipt-1",
                "verifier-source-grounding-1",
                "verifier-source-grounding-receipt-1",
            ),
            emitted_schema_ids=("verifier-global-cycle-assessment-receipt-1",),
            supported_relations=("relation:assesses-global-cycles",),
            domain_tags=("cycle", "experimental", "graph", "grounding"),
            additional_prerequisites=(
                f"EXACT_SOURCE_GROUNDING_PROFILE:{_SOURCE_GROUNDING_PROFILE_DIGEST}",
                f"EXACT_RELATION_BOUNDARY_PROFILE:{_RELATION_BOUNDARY_PROFILE_DIGEST}",
            ),
            freshness_behavior="Each call rechecks every selected relation and its separately grounded semantic source, then recomputes bounded graph facets from supplied retained bytes.",
            transformation_loss="Support cycles, undirected equation or constraint loops, and explicit backward-time relations remain separate facets; no causal direction is inferred.",
            failure_behavior="Missing or ungrounded material and exhausted work remain UNKNOWN; digest, receipt, or semantic substitution remains INVALID; declared constraint inconsistency remains CONFLICTED.",
            claim_boundary="A planned match does not run global-cycle assessment. An ASSESSED finite graph does not establish physical causation, whole-system consistency, completeness, safety, or behavior outside selected relations.",
        ),
        _component(
            "component:artifact-network-global-cycle-receipt-rechecker",
            "Experimental global-cycle receipt rechecker",
            ComponentKind.CHECKER,
            "verifier.interoperability.global_cycle_assessment:recheck_global_cycle_receipt",
            "vstd-global-cycle",
            "Verifier Standard experimental grounded finite-graph cycle replay",
            ("global-cycle receipt", "exact declaration and grounded relation materials"),
            (
                "verifier-global-cycle-assessment-1",
                "verifier-cycle-relation-semantics-1",
                _SOURCE_GROUNDING_PROFILE_DIGEST,
                _RELATION_BOUNDARY_PROFILE_DIGEST,
            ),
            (
                "verifier-global-cycle-assessment-1 canonical immutable declaration bytes",
                "verifier-global-cycle-assessment-receipt-1 canonical immutable receipt bytes",
                "digest-keyed typed CycleRelationMaterial mapping",
                "bounded maximum-work integer",
            ),
            ("GlobalCycleReceipt",),
            ("ASSESSED", "CONFLICTED", "UNKNOWN", "INVALID"),
            ("mechanism:global-cycle-receipt-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=(
                "verifier-cycle-relation-semantics-1",
                "verifier-global-cycle-assessment-1",
                "verifier-global-cycle-assessment-receipt-1",
                "verifier-relation-boundary-receipt-1",
                "verifier-source-grounding-1",
                "verifier-source-grounding-receipt-1",
            ),
            supported_relations=("relation:rechecks-global-cycle-receipt",),
            domain_tags=("cycle", "experimental", "graph", "receipt"),
            additional_prerequisites=(
                f"EXACT_SOURCE_GROUNDING_PROFILE:{_SOURCE_GROUNDING_PROFILE_DIGEST}",
                f"EXACT_RELATION_BOUNDARY_PROFILE:{_RELATION_BOUNDARY_PROFILE_DIGEST}",
            ),
            freshness_behavior="Each call rebuilds all cycle facets from current retained materials and requires exact canonical receipt bytes under the same work bound.",
            transformation_loss="Receipt equality preserves the assessor's separate cycle facets and finite bounds but adds no causal interpretation or independent implementation evidence.",
            failure_behavior="Malformed records and any replay mismatch raise GlobalCycleError; reproduced CONFLICTED and UNKNOWN states remain conflicted or unknown.",
            claim_boundary="A planned match does not run receipt rechecking. Receipt reproduction does not establish physical causation, whole-system consistency, completeness, safety, or implementation independence.",
        ),
        _component(
            "component:artifact-network-bounded-completeness-assessor",
            "Experimental source-grounded bounded-completeness assessor",
            ComponentKind.CHECKER,
            "verifier.interoperability.bounded_completeness:assess_bounded_completeness",
            "vstd-bounded-completeness",
            "Verifier Standard experimental finite-denominator completeness replay",
            ("exact bounded-completeness declaration", "grounded denominator and member observations"),
            (
                "verifier-bounded-completeness-mechanism-profile-1",
                _BOUNDED_COMPLETENESS_PROFILE_DIGEST,
                _SOURCE_GROUNDING_PROFILE_DIGEST,
            ),
            (
                "verifier-bounded-completeness-1 canonical immutable declaration bytes",
                "digest-keyed immutable denominator, observation, and grounding evidence mapping",
            ),
            ("BoundedCompletenessReceipt",),
            ("COMPLETE", "INCOMPLETE", "UNKNOWN", "INVALID"),
            ("mechanism:bounded-completeness-assessment",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=(
                "verifier-bounded-completeness-1",
                "verifier-bounded-completeness-denominator-1",
                "verifier-bounded-completeness-observations-1",
                "verifier-source-grounding-1",
                "verifier-source-grounding-receipt-1",
            ),
            emitted_schema_ids=("verifier-bounded-completeness-receipt-1",),
            supported_relations=("relation:assesses-bounded-completeness",),
            domain_tags=("completeness", "experimental", "finite-set", "grounding"),
            additional_prerequisites=(
                f"EXACT_RULE_PROFILE:{_BOUNDED_COMPLETENESS_PROFILE_DIGEST}",
                f"EXACT_SOURCE_GROUNDING_PROFILE:{_SOURCE_GROUNDING_PROFILE_DIGEST}",
            ),
            freshness_behavior="Each call rechecks the exact externally grounded finite census and every declared member observation from supplied retained evidence.",
            transformation_loss="COMPLETE is relative only to one exact grounded finite denominator and declared disposition checker; it is not open-world or semantic completeness.",
            failure_behavior="Extra observations, circular or malformed grounding, and substituted evidence remain INVALID; missing members remain INCOMPLETE; unsupported or exhausted evidence remains UNKNOWN.",
            claim_boundary="A planned match does not run bounded-completeness assessment. COMPLETE does not establish an exhaustive real-world denominator, source truth, correctness of member claims, or future completeness.",
        ),
        _component(
            "component:artifact-network-bounded-completeness-receipt-rechecker",
            "Experimental bounded-completeness receipt rechecker",
            ComponentKind.CHECKER,
            "verifier.interoperability.bounded_completeness:recheck_bounded_completeness_receipt",
            "vstd-bounded-completeness",
            "Verifier Standard experimental finite-denominator completeness replay",
            ("bounded-completeness receipt", "exact declaration and retained evidence"),
            (
                "verifier-bounded-completeness-mechanism-profile-1",
                _BOUNDED_COMPLETENESS_PROFILE_DIGEST,
                _SOURCE_GROUNDING_PROFILE_DIGEST,
            ),
            (
                "verifier-bounded-completeness-1 canonical immutable declaration bytes",
                "verifier-bounded-completeness-receipt-1 canonical immutable receipt bytes",
                "digest-keyed immutable denominator, observation, and grounding evidence mapping",
            ),
            ("BoundedCompletenessReceipt",),
            ("COMPLETE", "INCOMPLETE", "UNKNOWN", "INVALID"),
            ("mechanism:bounded-completeness-receipt-recheck",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=(
                "verifier-bounded-completeness-1",
                "verifier-bounded-completeness-denominator-1",
                "verifier-bounded-completeness-observations-1",
                "verifier-bounded-completeness-receipt-1",
                "verifier-source-grounding-1",
                "verifier-source-grounding-receipt-1",
            ),
            supported_relations=("relation:rechecks-bounded-completeness-receipt",),
            domain_tags=("completeness", "experimental", "finite-set", "receipt"),
            additional_prerequisites=(
                f"EXACT_RULE_PROFILE:{_BOUNDED_COMPLETENESS_PROFILE_DIGEST}",
                f"EXACT_SOURCE_GROUNDING_PROFILE:{_SOURCE_GROUNDING_PROFILE_DIGEST}",
            ),
            freshness_behavior="Each call rebuilds the complete assessment from current retained evidence and requires exact canonical receipt reproduction.",
            transformation_loss="Receipt equality is limited to the same exact finite denominator, profile, and reference mechanism and does not widen completeness scope.",
            failure_behavior="Malformed records and any deterministic replay mismatch raise BoundedCompletenessError; reproduced INCOMPLETE and UNKNOWN remain incomplete or unknown.",
            claim_boundary="A planned match does not run receipt rechecking. Receipt reproduction does not establish an exhaustive real-world denominator, source truth, future completeness, or implementation independence.",
        ),
        _component(
            "component:artifact-network-runtime-authority-correspondence-assessor",
            "Experimental runtime-authority correspondence assessor",
            ComponentKind.CHECKER,
            "verifier.interoperability.runtime_authority_correspondence:build_runtime_authority_correspondence_receipt",
            "vstd-runtime-authority",
            "Verifier Standard experimental retained-trace and native-process replay",
            ("exact runtime-authority declaration", "retained model, artifact, trace, and deriver evidence"),
            (
                "verifier-runtime-authority-correspondence-profile-1",
                "verifier-retained-event-trace-replay-1",
                _RUNTIME_AUTHORITY_PROFILE_DIGEST,
                _DERIVER_SELF_STATUS_PROFILE_DIGEST,
            ),
            (
                "verifier-runtime-authority-correspondence-1 canonical immutable declaration bytes",
                "digest-keyed immutable retained evidence dictionary",
                "optional local deriver executable filesystem path",
            ),
            ("RuntimeAuthorityReceipt",),
            ("ESTABLISHED", "REFUTED", "COMPLETE", "INCOMPLETE", "UNKNOWN", "INVALID"),
            ("mechanism:runtime-authority-correspondence-assessment",),
            (InteractionMode.LIVE_MUTATING,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=(
                "verifier-authority-model-1",
                "verifier-deriver-self-status-1",
                "verifier-deriver-self-status-receipt-1",
                "verifier-runtime-authority-correspondence-1",
                "verifier-runtime-authority-trace-1",
            ),
            emitted_schema_ids=(
                "verifier-runtime-authority-correspondence-receipt-1",
            ),
            supported_relations=("relation:assesses-runtime-authority-correspondence",),
            domain_tags=("authority", "execution", "experimental", "runtime"),
            additional_prerequisites=(
                f"EXACT_RULE_PROFILE:{_RUNTIME_AUTHORITY_PROFILE_DIGEST}",
                f"EXACT_DERIVER_PROFILE:{_DERIVER_SELF_STATUS_PROFILE_DIGEST}",
                "EXPLICIT_PROCESS_EXECUTION_AUTHORIZATION",
                "PUBLIC_NON_SECRET_ENVIRONMENT",
                "SUPPORTED_WINDOWS_NATIVE_RUNTIME",
            ),
            freshness_behavior="A supported call rechecks one exact deriver execution against the local executable, then replays its exact standard-output trace over the finite authority model.",
            transformation_loss="The receipt covers only observed events and an explicit finite transition denominator; it is not an attestation of deployment, continuity, actor identity, or all runtime behavior.",
            failure_behavior="Malformed or substituted bytes remain INVALID, observed correspondence disagreement remains REFUTED, incomplete finite coverage remains INCOMPLETE, and unsupported execution remains UNKNOWN.",
            claim_boundary="A planned match does not authorize or run the native process. ESTABLISHED correspondence and COMPLETE finite coverage do not establish authorization, actual deployment, source correctness, secrecy, safety, or unobserved behavior.",
        ),
        _component(
            "component:artifact-network-runtime-authority-correspondence-receipt-rechecker",
            "Experimental runtime-authority correspondence receipt rechecker",
            ComponentKind.CHECKER,
            "verifier.interoperability.runtime_authority_correspondence:recheck_runtime_authority_correspondence_receipt",
            "vstd-runtime-authority",
            "Verifier Standard experimental retained-trace and native-process replay",
            ("runtime-authority correspondence receipt", "local deriver executable bytes"),
            (
                "verifier-runtime-authority-correspondence-profile-1",
                "verifier-retained-event-trace-replay-1",
                _RUNTIME_AUTHORITY_PROFILE_DIGEST,
                _DERIVER_SELF_STATUS_PROFILE_DIGEST,
            ),
            (
                "verifier-runtime-authority-correspondence-receipt-1 canonical immutable receipt bytes",
                "optional local deriver executable filesystem path",
            ),
            ("ReceiptRecheck",),
            ("ESTABLISHED", "UNKNOWN", "INVALID"),
            ("mechanism:runtime-authority-correspondence-receipt-recheck",),
            (InteractionMode.LIVE_MUTATING,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            accepted_schema_ids=(
                "verifier-runtime-authority-correspondence-receipt-1",
            ),
            supported_relations=(
                "relation:rechecks-runtime-authority-correspondence-receipt",
            ),
            domain_tags=("authority", "execution", "experimental", "receipt", "runtime"),
            additional_prerequisites=(
                f"EXACT_RULE_PROFILE:{_RUNTIME_AUTHORITY_PROFILE_DIGEST}",
                f"EXACT_DERIVER_PROFILE:{_DERIVER_SELF_STATUS_PROFILE_DIGEST}",
                "EXPLICIT_PROCESS_EXECUTION_AUTHORIZATION",
                "PUBLIC_NON_SECRET_ENVIRONMENT",
                "SUPPORTED_WINDOWS_NATIVE_RUNTIME",
            ),
            freshness_behavior="Each supported call reconstructs retained evidence from the receipt and reruns the bound deriver execution before requiring exact receipt reproduction.",
            transformation_loss="Reproduction uses the same reference mechanisms and local executable; it is not independent implementation, deployment, custody, or all-runtime evidence.",
            failure_behavior="Malformed, forged, or nonreproducing receipts remain INVALID; unsupported or resource-limited replay remains UNKNOWN; only exact reconstruction yields ESTABLISHED.",
            claim_boundary="A planned match does not authorize or run receipt rechecking. Receipt reproduction does not establish authorization, actual deployment, source correctness, secrecy, safety, or implementation independence.",
        ),
        _component(
            "component:provenance-policy-verifier",
            "Recorded provenance policy verifier",
            ComponentKind.POLICY,
            "verifier.data.policy:ProvenancePolicyVerifier",
            "provenance-policy",
            "Verifier Standard provenance policy engine",
            ("recorded provenance hypergraph",),
            ("POL-NO-REVOKED-ANCESTORS", "POL-ALL-ANCESTORS-VALID", "POL-APPROVED-LICENSES"),
            ("typed-ProvenanceHypergraph-unversioned", "target artifact identifier"),
            ("PolicyEvaluationResult",),
            ("VERIFIED", "FALSIFIED"),
            (
                "mechanism:policy-all-ancestors-valid",
                "mechanism:policy-approved-licenses",
                "mechanism:policy-no-revoked-ancestors",
            ),
            (InteractionMode.STATIC,),
            domain_tags=("policy", "provenance", "reference"),
            freshness_behavior="Each policy reads the supplied in-memory recorded graph state.",
            transformation_loss="The typed method arguments have no standalone versioned input schema.",
            failure_behavior="Encoding/direct-computation disagreement raises rather than selecting a convenient result.",
            claim_boundary="A planned match does not run policy verification or establish hidden ancestry, authentic statuses, or legal conclusions.",
        ),
        _component(
            "component:scitt-evidence-consumer",
            "SCITT native-evidence consumer",
            ComponentKind.ADAPTER,
            "verifier.interoperability.scitt.adapter:consume_scitt_evidence",
            "vstd-scitt-composition",
            "Experimental VSTD and SCITT mapping",
            ("normalized native SCITT verifier output",),
            ("vstd-scitt-interop-experimental-0.1",),
            ("ScittRegistrationTemplate", "native verifier result mapping"),
            ("bounded SCITT transparency evidence mapping",),
            ("REGISTERED", "MISSING", "STALE", "CONFLICTED", "REVOKED", "SUPERSEDED", "UNKNOWN", "INVALID"),
            ("mechanism:scitt-native-evidence-consumption",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            domain_tags=("experimental", "software-supply-chain", "transparency"),
            freshness_behavior="The adapter preserves supplied registration time and native freshness state.",
            transformation_loss="The normalized mapping is not a native Concise Binary Object Representation or signature verifier.",
            failure_behavior="Incomplete, mismatched, stale, or contradictory evidence remains non-registered.",
            claim_boundary="A planned match does not run a SCITT verifier or establish registration, payload truth, or VSTD conformance.",
        ),
        _component(
            "component:scitt-result-composer",
            "VSTD and SCITT adjacent-result composer",
            ComponentKind.TRANSLATOR,
            "verifier.interoperability.scitt.adapter:compose_results",
            "vstd-scitt-composition",
            "Experimental VSTD and SCITT mapping",
            ("native VSTD result", "normalized SCITT evidence"),
            ("vstd-scitt-interop-experimental-0.1",),
            ("VstdVerificationEvidence", "ScittVerificationEvidence", "VstdScittPayload"),
            ("CompositionResult",),
            ("PASS", "FAIL", "UNKNOWN", "CONFLICTED"),
            ("mechanism:vstd-scitt-adjacent-composition",),
            (InteractionMode.OFFLINE_REPLAY,),
            lifecycle=ComponentLifecycle.EXPERIMENTAL,
            domain_tags=("composition", "experimental", "software-supply-chain"),
            freshness_behavior="Composition uses only the supplied current native evidence objects.",
            transformation_loss="Composition retains native results but cannot strengthen either source mechanism.",
            failure_behavior="Every nonpassing or mismatched source state is preserved or lowered.",
            claim_boundary="A planned match does not run either native verifier or establish payload truth, safety, or VSTD conformance.",
        ),
    )
    return InteroperabilityComponentRegistry(
        registry_version=REFERENCE_CATALOG_VERSION,
        components=components,
    )


__all__ = [
    "REFERENCE_CATALOG_CLAIM_BOUNDARY",
    "REFERENCE_CATALOG_VERSION",
    "reference_component_registry",
]
